### ISSUE TITLE
When using components individually an error is thrown

### ISSUE THREAD

**Issue by gensmann** [bootstrap-vue/bootstrap-vue#1103] opened 2017-09-23 20:21 UTC
When using components individually an error is thrown:

'''
./node_modules/bootstrap-vue/lib/components/form-group.vue
Module build failed: ReferenceError: Unknown plugin "external-helpers" specified in "[Path redacted]/module-ui/node_modules/bootstrap-vue/lib/.babelrc" at 0, attempted to resolve relative to "[Path redacted]/module-ui/node_modules/bootstrap-vue/lib"
    at Array.map (<anonymous>)
'''

It seems to fix it, to do a npm install in the package dir for bootstrap-vue, so maybe it's due to something not getting installed when using bootstrap-vue as a package in another package (dev-dependencies?)

**Comment by djzara** [comment] 2017-09-25 13:48
I'm have the exact same issue as above using:

boostrap ^4.0.0-beta
boostrap-vue ^1.0.0-beta.9

**Comment by alexsasharegan** [comment] 2017-09-28 04:46
@robcresswell and I worked through this recently. I believe the easiest way to solve this was to use the babel config in webpack. This bypasses all the `.babelrc` configs that will trigger the lookup for `babelHelpers`.

**Comment by robcresswell** [comment] 2017-09-28 07:17
Specifically, you need to use `babelrc: false` in your babel-loader options, then pass the babel options via your webpack config. Thanks for the heads up @alexsasharegan :)

**Comment by askz** [comment] 2017-10-02 14:09
It worked for me with http://babeljs.io/docs/plugins/external-helpers/ added in your webpack config.
Then npm install --save-dev lodash.startcase  
And voila!

**Comment by robcresswell** [comment] 2017-10-03 12:57
@askz That's great and all, but now you have extra dependencies and webpack config for a single lib, which isn't always desirable :)

**Comment by milenon** [comment] 2017-10-03 13:29
If this issue can't be fixed can you describe in the documentation what configuration changes should be done if we want to include components individually.

**Comment by djzara** [comment] 2017-10-03 13:33
I'm with @robcresswell in that this creates extra configs to do something that should be out of the box, such as with the 0.26.0 version of bootstrap-vue, which required no extra configuration. No reports of missing dependencies.

**Comment by xxRockOnxx** [comment] 2017-10-13 04:55
is
> * vue-functional-data-merge/dist/lib.common.js in ./node_modules/bootstrap-vue/lib/utils/index.js

included in this issue also? Have moved my .babelrc config into my webpack already and included `lodash.startcase` and `external-helpers` in my dependencies.

Is the version from `dev` branch somehow solved this? I don't feel adding dependencies that should be dependencies of a package... unless no choice.

**Comment by fbmfbm** [comment] 2017-10-16 13:10
Hi all,

Same thing for me  :" babelhelpers is not defined " error after update with error and run npm install in the package dir.

Any fix for this ?

Thank's

**Comment by robcresswell** [comment] 2017-10-16 13:45
@fbmfbm See my post above.

> Specifically, you need to use babelrc: false in your babel-loader options, then pass the babel options via your webpack config

**Comment by xxRockOnxx** [comment] 2017-10-16 14:21
@fbmfbm that's what I did actually. I moved `.babelrc` contents inside webpack but with that error still

**Comment by fbmfbm** [comment] 2017-10-16 14:24
@robcresswell  Thanks i have try that ... but as said RockOnxx the error is still present

**Comment by djzara** [comment] 2017-10-16 14:28
FWIW, this issue is ongoing when using Laravel 5.5. I realize this is an issue to bring up with the Laravel Mix folks, but I would think the library should account for its own dependencies.

**Comment by fbmfbm** [comment] 2017-10-16 14:38
@djzara Yes, that my case in Laravel 5.5. Have you a tip to resolve that ?

**Comment by djzara** [comment] 2017-10-16 14:47
@fbmfbm still working on it, I'll try to see if it'll make sense to open an issue over there

**Comment by xxRockOnxx** [comment] 2017-10-16 14:51
@djzara what does `laravel-mix` has to do with this? it has `webpackConfig` as option where we can put the babel config like:

```
webpackConfig: {
  module: {
    rules: [{
      test: /\.js$/,
      include: /bootstrap-vue/,
      use: {
        loader: 'babel-loader',
        ............
      }
    }]
  }
}

```

**Comment by djzara** [comment] 2017-10-16 14:55
@xxRockOnxx lack of seamlessness. Vue is part of the install, and as such it would make sense that anything vue related works out of the box. I tried what you posted above, but couldn't get it to work right. I'll be happy to try again when I can

**Comment by xxRockOnxx** [comment] 2017-10-16 15:00
@djzara I know that doesn't work unlike what it is expected but I was wondering why you mentioned `laravel-mix` has something to do with this. Does regular webpack (by regular i mean without laravel-mix) work?

**Comment by djzara** [comment] 2017-10-16 15:02
@xxRockOnxx oh sorry, I brought it up because it's the most common use case I can think of, just as an aside, as that's what I'm trying to get working with the suggestions here. Regular seems to work ok.

**Comment by fbmfbm** [comment] 2017-10-17 14:43
Well, i install babel_helper as in the link http://babeljs.io/docs/plugins/external-helpers/

and an "fs" module not found is now the result. No way with install it. So after found some info i test to insert 
`

mix.webpackConfig({


    node: {
        fs: "empty"
    },

});

`

in webpack-mix and  the fs error desappear, but other one is now present 

This relative module was not found:

* ../../package in ./node_modules/babel-core/lib/api/node.js


..... So now for this time and i'm in stresse on a production project !!
No one as some idea to bypass that for this moment ?

**Comment by robcresswell** [comment] 2017-10-17 14:51
@fbmfbm Just install the project as a plugin if you're that desperate to progress. Its the recommend process anyway. You're currently following a non-recommended workflow on a beta library and getting stressed at roadbumps lol 😄

**Comment by fbmfbm** [comment] 2017-10-17 16:00
That's the stress ;)) i'm loosing all rationality.

Use it as a plugin to the job .

Thank's.

**Comment by tmorehouse** [comment] 2017-11-01 17:54
Release v1.0.0 (coming soon), will make it much easier to import individual components and also import component groups (i.e. card and all its sub-components) as a Vue plugin.

**Comment by fbmfbm** [comment] 2017-11-01 18:00
Great job !
i'm waiting for it.

**Comment by robcresswell** [comment] 2017-11-01 18:03
@tmorehouse That's great; thanks for taking our feedback on board. Really appreciate all the hard work going into this lib.

**Comment by djzara** [comment] 2017-11-01 18:05
@tmorehouse Can;t wait, thanks so much!!!

**Comment by infostreams** [comment] 2017-11-03 14:10
I got it to work after running

```bash
npm install webpack-babel-external-helpers --save-dev
npm install lodash.startcase --save-dev 
```

and adjusting my webpack.mix.js to

```js
const path = require("path");

mix.options({processCssUrls: false})
    .webpackConfig({
        module: {
            rules: [
                { // this is here because of https://github.com/bootstrap-vue/bootstrap-vue/issues/564#issuecomment-311419078
                    test: /\.js$/,
                    include: [
                        path.resolve(__dirname, "resources/assets/js/"), // your application source code root
                        path.resolve(__dirname, 'node_modules/bootstrap-vue'),
                    ],
                    use: {
                        loader: "babel-loader",
                        options: {
                            babelrc: false
                        }
                    }
                },
            ]
        }
    })
```

Reconstructed from last week's BASH history & the above comment thread, so perhaps I missed a step. Hope it's helpful to anyone anyway.

**Comment by djzara** [comment] 2017-11-03 14:21
@infostreams I did exactly the same and it worked for me as well. My only issue is that, given that this should be a drop in library for Vue, we shouldn't have to take those extra steps. babel ignores node_modules by design, so having to go around that is not optimal. As the bootstrap-vue maintainers have said, we could just use the individual builds from the full build, as it's small in file size, but I disagree that that's a good idea, and not because of file size. It's a matter of including just what we need instead of everything all at once to help modularize.

Still, I'm glad we seem to have this all figured out. Thanks so much everyone!

**Comment by infostreams** [comment] 2017-11-03 14:24
Sure, I completely agree and I'm very happy that it will be properly supported in 1.0 (looking forward!). In the mean time, I hope the code above will save someone an hour of head-scratching 😉

**Comment by djzara** [comment] 2017-11-03 14:32
@infostreams definitely saved me!! thanks so much!!

**Closed** 2017-11-06 19:36 UTC
Labels: Status: Coming Soon, Version: 1.x
