### ISSUE TITLE
Spread operator broke the build

### ISSUE THREAD

**Issue by nonDeath** [bootstrap-vue/bootstrap-vue#685] opened 2017-07-12 00:12 UTC
I can't do a success build when a run `npm run dev` because the operator spread `...` is not compatible.

I try do the next:

1. Change presets to es2015 
1. Install `babel-plugin-transform-object-rest-spread` and then include in plugins on babelrc file.

Nothing of this work fine for me.

My package.json

```json
{
  "name": "bootstrap-vue",
  "version": "1.0.0",
  "description": "A Vue.js project",
  "author": "Marcelo <marceloaldo@gmail.com>",
  "private": true,
  "scripts": {
    "dev": "node build/dev-server.js",
    "start": "node build/dev-server.js",
    "build": "node build/build.js"
  },
  "dependencies": {
    "bootstrap-vue": "^0.18.0",
    "vue": "^2.3.3"
  },
  "devDependencies": {
    "autoprefixer": "^6.7.2",
    "babel-core": "^6.22.1",
    "babel-loader": "^6.2.10",
    "babel-plugin-transform-object-rest-spread": "^6.23.0",
    "babel-plugin-transform-runtime": "^6.22.0",
    "babel-preset-env": "^1.3.2",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-stage-2": "^6.22.0",
    "babel-register": "^6.22.0",
    "chalk": "^1.1.3",
    "connect-history-api-fallback": "^1.3.0",
    "copy-webpack-plugin": "^4.0.1",
    "css-loader": "^0.28.0",
    "eventsource-polyfill": "^0.9.6",
    "express": "^4.14.1",
    "extract-text-webpack-plugin": "^2.0.0",
    "file-loader": "^0.11.1",
    "friendly-errors-webpack-plugin": "^1.1.3",
    "html-webpack-plugin": "^2.28.0",
    "http-proxy-middleware": "^0.17.3",
    "opn": "^4.0.2",
    "optimize-css-assets-webpack-plugin": "^1.3.0",
    "ora": "^1.2.0",
    "rimraf": "^2.6.0",
    "semver": "^5.3.0",
    "shelljs": "^0.7.6",
    "url-loader": "^0.5.8",
    "vue-loader": "^12.1.0",
    "vue-style-loader": "^3.0.1",
    "vue-template-compiler": "^2.3.3",
    "webpack": "^2.6.1",
    "webpack-bundle-analyzer": "^2.2.1",
    "webpack-dev-middleware": "^1.10.0",
    "webpack-hot-middleware": "^2.18.0",
    "webpack-merge": "^4.1.0"
  },
  "engines": {
    "node": ">= 4.0.0",
    "npm": ">= 3.0.0"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8"
  ]
}
```
My .babelrc file

```javascript
{
  "presets": [
    ["env", {
      "modules": false,
      "targets": {
        "browsers": ["> 1%", "last 2 versions", "not ie <= 8"]
      }
    }],
    "stage-2"
  ],
  "plugins": ["transform-runtime", "transform-object-rest-spread"],
  "env": {
    "test": {
      "presets": ["env", "stage-2"],
      "plugins": ["istanbul"]
    }
  }
}
```
The `npm run dev` error

```bash

 ERROR  Failed to compile with 1 errors                                 20:59:34

 error  in ./~/bootstrap-vue/lib/mixins/dropdown.js

Module parse failed: /home/marcelo/Documentos/www/gh/bootstrap-vue/node_modules/bootstrap-vue/lib/mixins/dropdown.js Unexpected token (101:8)
You may need an appropriate loader to handle this file type.
|     },

```
My node and npm versions

```bash
$ node -v
v7.2.0
```
```bash
$ npm -v
v4.0.2
```

**Comment by alexsasharegan** [comment] 2017-07-12 00:25
The distribution files included in the project are compiled with object.assign, not spread operator. Is this a fork of bootstrap-vue, or a project using bootstrap-vue?

**Comment by nonDeath** [comment] 2017-07-12 00:30
Is a project using bootstap-vue. From clean install with `vue-init` cli tool.

**Comment by alexsasharegan** [comment] 2017-07-12 00:35
Gotcha, the name in package.json threw me. Can you include the code where you import bootstrapvue?

I'm guessing you're importing straight from the source code, in which case you will have to do the setup work in your build to transpire the source to es5.

**Comment by alexsasharegan** [comment] 2017-07-12 00:36
Maybe also include webpack config as well.

**Comment by alexsasharegan** [comment] 2017-07-12 00:43
If you have the project up on github, I can take a closer look. When I get home.

**Comment by nonDeath** [comment] 2017-07-12 01:27
Thanks @alexsasharegan, i try change the import, i guess its wrong

**Comment by alexsasharegan** [comment] 2017-07-12 01:35
Did you get it worked out then? If you want to paste your import statements, I'd be happy to give you some pointers. I'll close this if it's all figured out though.

**Comment by nonDeath** [comment] 2017-07-12 01:43
I changed it to this code, and success the build!
```javascript
<template>
  <div id="app">
    <img src="./assets/logo.png" @click="modalShow = !modalShow">
    <hello></hello>

    <b-modal v-model="modalShow"></b-modal>
  </div>
</template>

<script>
import Hello from './components/Hello'
import {bModal} from 'bootstrap-vue';

export default {
  name: 'app',
  components: {
    Hello,
    'b-modal': bModal
  },
  data: () => ({
    modalShow: false
  })
}
</script>
```

But i'm working around on a new error.
```
[Vue warn]: Unknown custom element: <modal>
```

**Comment by alexsasharegan** [comment] 2017-07-12 02:07
So I would recommend using your entry point file _(probably something like `app.js`)_ to include bootstrap-vue.

```js
// app.js (or whatever you app entry point file is called)
import Vue from "vue";
import BootstrapVue from "bootstrap-vue";

Vue.use(BootstrapVue);
```

Now back to your file:
```html
<template>
  <div id="app">
    <img src="./assets/logo.png" @click="modalShow = !modalShow">
    <hello></hello>

    <b-modal v-model="modalShow"></b-modal>
  </div>
</template>

<script>
import Hello from './components/Hello';

export default {
  name: 'app',
  components: {
    Hello,
  },
  data: () => ({
    modalShow: false
  })
}
</script>
```

**Comment by alexsasharegan** [comment] 2017-07-12 02:19
When you import `"Bootstrap-vue"`, node/webpack will attempt to resolve this use the package name first, then if it finds a package named such, it will return whatever is specified in the `pakcage.json`'s `"main"` property. If nothing is specified, it will regular to the package's `index.js` _(if there is one at the root level)_.

**Comment by nonDeath** [comment] 2017-07-12 02:27
I make it work! Thanks!!!

**Comment by alexsasharegan** [comment] 2017-07-12 02:39
Awesome!

**Closed by alexsasharegan** 2017-07-12 02:39 UTC

**Comment by dfsq** [comment] 2017-07-17 15:00
For those who don't want to import entire bootstrap-vue and wants to use only `bModal` component, you need to import it first and then register this component manually yourself:

    import bModal from 'bootstrap-vue/lib/components/modal.vue'
    Vue.component('b-modal', bModal)

**Comment by alexsasharegan** [comment] 2017-07-17 15:15
@dfsq, importing from the component index file should work as well if you are using es6 modules.

```js
import { bModal } from "bootstrap-vue/lib/components"
```

**Comment by alexsasharegan** [comment] 2017-07-17 15:16
But you would have to register it per component or globally for usage.

**Comment by More4ever** [comment] 2017-07-20 14:13
I reproduce this bug when tried to use only dropdown component. What to do if I don't want to use full package but only some components?

```
<template>
  <header>
    <b-dropdown text="TOOLS"></b-dropdown>
    <router-link to="/">Home</router-link>
    <router-link :to="{name: 'auth.login'}">Login</router-link>
  </header>
</template>
<script>

  import {bDropdown} from 'bootstrap-vue/lib/components'
  export default {
    name: 'AppHeader',
    components: {
      bDropdown,
    },
  };
</script>
```

this code leeds to error, but in my files I use spread operator without any error:
```
ERROR in ./~/bootstrap-vue/lib/mixins/dropdown.js
Module parse failed: xxx\node_modules\bootstrap-vue\lib\mixins\dropdown.js Unexpected token (101:8)
You may need an appropriate loader to handle this file type.
|     },
|     methods: {
|         ...clickOut.methods,
|         noop() {
|             // Do nothing event handler (used in visible watch)
```

Dependencies part of `package.json`:
```
  "dependencies": {
    "axios": "^0.16.2",
    "bootstrap": "^4.0.0-alpha.6",
    "bootstrap-vue": "^0.18.0",
    "dotenv": "^4.0.0",
    "pdfjs-dist": "^1.8.525",
    "vue": "^2.3.3",
    "vue-router": "^2.3.1",
    "vuedraggable": "^2.14.1"
  },
```

**Comment by tankbusta** [comment] 2017-08-09 19:27
I'm having the same issues as @More4ever. I use the spread operator just fine in my vue components but individually loading components from bootstrap-vue raise that unexpected token error. 

Registering bootstrap-vue globally works but I really am only interested in a few of the components.

**Comment by mosinve** [comment] 2017-08-09 19:34
Since the object spread syntax is still a Stage 3 proposal for ECMAScript you'll need to use a transpiler such as Babel to use it in production. You can use your existing babel preset, install babel-plugin-transform-object-rest-spread and add it individually to the plugins array in your .babelrc.

```
{
  "presets": ["es2015"],
  "plugins": ["transform-object-rest-spread"]
}

```
Note that this is still an experimental language feature proposal so it may change in the future.

**Comment by tankbusta** [comment] 2017-08-09 19:39
I am using Babel and have that plugin installed and still get the error

.babel.rc
```
{
  "presets": [
    ["env", { "modules": false }],
    "stage-2"
  ],
  "plugins": ["transform-runtime", "transform-object-rest-spread"],
  "env": {
    "test": {
      "presets": ["env", "stage-2"],
      "plugins": [ "istanbul" ]
    }
  }
}
```

package.json
```
...
"devDependencies": {
    "autoprefixer": "^6.7.2",
    "babel-core": "^6.22.1",
    "babel-eslint": "^7.1.1",
    "babel-loader": "^6.2.10",
    "babel-plugin-transform-object-rest-spread": "^6.23.0",
    "babel-plugin-transform-runtime": "^6.22.0",
    "babel-preset-env": "^1.3.2",
    "babel-preset-stage-2": "^6.22.0",
    "babel-register": "^6.22.0",
    ....
}
...
```

**Comment by mosinve** [comment] 2017-08-09 19:41
and you should add `node_modules\bootstrap-vue\lib\` folder to babel scope at webpack.config.js

```
            {
                test: /\.js$/,
                loader: 'babel-loader',
                // For using direct BootstrapVue *.vue components
                include: [resolve('src'), resolve('test'), **resolve('node_modules/bootstrap-vue/lib')**],
            },
```

**Comment by tankbusta** [comment] 2017-08-09 19:45
Adding that to my webpack.config.js fixed it @mosinve. Thanks!
