### ISSUE TITLE
"You may need an appropriate loader to handle this file type."

### ISSUE THREAD

**Issue by xtrimf** [bootstrap-vue/bootstrap-vue#1047] opened 2017-09-13 15:13 UTC
Hi,

I used "`yarn add bootstrap-vue`"

Here is my main.js:
```
import Vue from 'vue';
import VueRouter from 'vue-router';
import BootstrapVue from 'bootstrap-vue';
import 'bootstrap-vue/dist/bootstrap-vue.css';
import 'bootstrap/dist/css/bootstrap.css';
import App from './App.vue';
import {routes} from './routes.js';
import {store} from './store/store';

Vue.use(VueRouter);
Vue.use(VueResource);
Vue.use();
Vue.use(BootstrapVue);
```

packages.json:
```
dependencies": {
    "bootstrap-vue": "^1.0.0-beta.7",
    "vue": "^2.4.2",
    "vue-router": "^2.7.0",
    "vuex": "^2.4.0"
  },
  "devDependencies": {
    "babel-core": "^6.0.0",
    "babel-loader": "^6.0.0",
    "babel-plugin-transform-object-rest-spread": "^6.23.0",
    "babel-preset-latest": "^6.0.0",
    "cross-env": "^3.0.0",
    "css-loader": "^0.25.0",
    "file-loader": "^0.9.0",
    "style-loader": "^0.18.2",
    "vue-loader": "^11.3.4",
    "vue-template-compiler": "^2.4.2",
    "webpack": "^2.2.0",
    "webpack-dev-server": "^2.2.0"
  }
```

but loading fails:
```
../node_modules/bootstrap-vue/dist/bootstrap-vue.css Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
.
.
.
/~/bootstrap-vue/dist/bootstrap-vue.css
Module parse failed: ../node_modules/bootstrap-vue/dist/bootstrap-vue.css Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
.
.
.
./~/bootstrap/dist/css/bootstrap.css
Module parse failed: ../node_modules/bootstrap/dist/css/bootstrap.css Unexpected character '@' (7:0)
You may need an appropriate loader to handle this file type.
```

**Comment by alexsasharegan** [comment] 2017-09-13 15:59
This is basically a duplicate of #949. Read through there for the how to add the rule for the css loader. I also have a couple links to the webpack plugins you'll need to install in there.

**Comment by xtrimf** [comment] 2017-09-13 16:15
I added these lines, but it didn't help...

here is my webpack config:
```
var path = require('path')
var webpack = require('webpack')

module.exports = {
  entry: './src/main.js',
  output: {
    path: path.resolve(__dirname, './dist'),
    publicPath: '/dist/',
    filename: 'build.js'
  },
  module: {
    rules: [
      {
        test: /\.vue$/,
        loader: 'vue-loader',
        options: {
          loaders: {
          }
          // other vue-loader options go here
        }
      },
      {
        test: /\.js$/,
        loader: 'babel-loader',
        exclude: /node_modules/
      },
      {test: /\.scss?$/, loaders: ['style-loader', 'css-loader', 'sass-loader']},
      {test: /\.css?$/, loaders: ['style-loader', 'css-loader', 'sass-loader']},
      {
        test: /\.(png|jpg|gif|svg)$/,
        loader: 'file-loader',
        options: {
          name: '[name].[ext]?[hash]'
        }
      }
    ]
  },
  resolve: {
    alias: {
      'vue$': 'vue/dist/vue.esm.js'
    }
  },
  devServer: {
    historyApiFallback: true,
    noInfo: true,
    host: '0.0.0.0'
  },
  performance: {
    hints: false
  },
  devtool: '#eval-source-map'
}

if (process.env.NODE_ENV === 'production') {
  module.exports.devtool = '#source-map'
  // http://vue-loader.vuejs.org/en/workflow/production.html
  module.exports.plugins = (module.exports.plugins || []).concat([
    new webpack.DefinePlugin({
      'process.env': {
        NODE_ENV: '"production"'
      }
    }),
    new webpack.optimize.UglifyJsPlugin({
      sourceMap: true,
      compress: {
        warnings: false
      }
    }),
    new webpack.LoaderOptionsPlugin({
      minimize: true
    })
  ])
}

```

**Comment by xtrimf** [comment] 2017-09-13 16:22
I also tried "npm install sass-loader --save-dev" and got this error now:
`Cannot find module 'node-sass'`

**Comment by alexsasharegan** [comment] 2017-09-14 06:16
Sass loader requires the node sass for node bindings to libsass. `npm I -D node-sass` to pick up that bundling dep as well.

**Comment by alexsasharegan** [comment] 2017-09-16 13:32
Is this still an issue, @xtrimf ? Reopen if you need further assistance.

**Closed by alexsasharegan** 2017-09-16 13:32 UTC
Labels: Status: Help Wanted, Type: Duplicate
