### ISSUE TITLE
Sort using two column keys instead of one

### ISSUE THREAD

**Issue by janswist** [bootstrap-vue/bootstrap-vue#3635] opened 2019-07-08 13:26 UTC
Is there any way to sort by two columns instead of just one? What I want to achieve is to sort two numeric columns where if two rows have the same value in the first column then they will be sorted by the value in second column.

I found `sort-compare`, but `key` argument seems to only accept one key. I think it's a common thing to do so maybe there is a way I can't see.

**Comment by tmorehouse** [comment] 2019-07-08 13:28
Currently `b-table` only supports sorting on a single field key at the moment, but it is on our road map to support multiple sort columns.

Duplicate of https://github.com/bootstrap-vue/bootstrap-vue/issues/2068

**Closed by tmorehouse** 2019-07-08 13:28 UTC
Labels: Type: Duplicate, Type: Feature request
