### ISSUE TITLE
Module not found: Error: Can't resolve 'lodash/get'

### ISSUE THREAD

**Issue by trylovetom** [bootstrap-vue/bootstrap-vue#1670] opened 2018-03-12 12:49 UTC
I've added BootstrapVue to my project. When trying to build i keep getting:
Module not found: Error: Can't resolve 'lodash/get' error.

**Comment by robcresswell** [comment] 2018-03-12 17:05
Please read the issue template and properly fill out your bug report so we can help, thanks! 😄

**Comment by rjmill** [comment] 2018-03-21 19:58
I'm experiencing the same issue. I'll add as much info as I can.

@robcresswell because of the nature of this bug, a "reduced test case" is trickier than I originally anticipated (which, unfortunately, means that reproducing it is tricky too.) I'll explain more, and hopefully you'll see what I mean. Hopefully my PR (#1697) helps illustrate the issue we're running into a bit better.

First off, the full error message:
```
ERROR in ./node_modules/bootstrap-vue/es/components/table/table.js
Module not found: Error: Can't resolve 'lodash/get' in '/home/rjmill/Development/build-chain/node_modules/bootstrap-vue/es/
components/table'
 @ ./node_modules/bootstrap-vue/es/components/table/table.js 4:0-29
 @ ./node_modules/bootstrap-vue/es/components/table/index.js
 @ ./node_modules/bootstrap-vue/es/components/index.js
 @ ./node_modules/bootstrap-vue/es/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server babel-polyfill ./src/main.js
```

OS: Arch Linux
Browser and version: **N/A - bootstrap-vue doesn't make it past the build step**
Version of bootsrap-vue: **2.0.0-rc.2**
~~Reduced test cases and~~ potential fixes: #1697
package manager: yarn
webpack version: 3.11.0

The issue is that **`lodash.get` is being imported as `lodash/get`, even though `lodash` is not in the package.json's `dependencies`.** The reason this isn't throwing an error on most projects is that `lodash` is often included in `node_modules`, either through `devDependencies` or as a dependency of something in `devDependencies`. `boostrap-vue` includes `lodash` in its `devDependencies`, which is why the unit tests are still working. I tried making a reduced test case with `vue-cli`, but the `webpack` template includes `lodash` in `node_modules` as a dependency of something in `devDependencies`, so `bootstrap-vue` works fine.

Even my project would include `lodash` v4.x by virtue of it being a dependency of a devDependency, **but** I have `lodash` v2.x in my `dependencies` to shim in for a legacy dependency. (In this case, `lodash` is being included in the parent library's `node_modules` instead of at the top level of my project's `node_modules`, as it would be normally.)

The end result is that `lodash/get` points to nothing in my project, and bootstrap-vue's table does not compile.

Hopefully #1697 will help show the issue more clearly than I'm being here. Let me know if you have any questions or want me to clarify anything :)

**Comment by rjmill** [comment] 2018-03-21 20:27
I figured out how to do a reduced(ish) test case:

## basically
Just add `lodash@2` to a project that's using bootstrap-vue.

## more precisely
Use vue-cli  to make a project with the **webpack-simple** template (**not** boostrap-vue/webpack-simple):
```
vue init webpack-simple reduced-test-case
cd reduced-test-case

yarn
yarn add bootstrap-vue
yarn add lodash@2

# overwrite `./src/main.js` to match this
cat << EOF > ./src/main.js
import Vue from 'vue'
import App from './App.vue'

// NOTE: or you can just add the following line via your text editor
import BootstrapVue from 'bootstrap-vue'

new Vue({
  el: '#app',
  render: h => h(App)
})
EOF

yarn run dev
```
The project should throw the error then.

**Comment by pi0** [comment] 2018-04-16 15:07
Should be fixed wit the latest rc.

**Closed by pi0** 2018-04-16 15:07 UTC
