### ISSUE TITLE
Issue using boostrap via npm

### ISSUE THREAD

**Issue by avilesasturias** [bootstrap-vue/bootstrap-vue#2634] opened 2019-02-18 12:20 UTC
Mac OSX issue using boostrap-vue
Failed to compile with 199 errors,
some of them:

These dependencies were not found:

* @babel/runtime/helpers/classCallCheck in ./node_modules/bootstrap-vue/es/directives/scrollspy/scrollspy.class.js, ./node_modules/bootstrap-vue/es/utils/tooltip.class.js and 2 others
* @babel/runtime/helpers/createClass in ./node_modules/bootstrap-vue/es/directives/scrollspy/scrollspy.class.js, ./node_modules/bootstrap-vue/es/utils/tooltip.class.js and 2 others
* @babel/runtime/helpers/defineProperty in ./node_modules/bootstrap-vue/es/components/button/button.js, ./node_modules/bootstrap-vue/es/components/button/button-close.js and 22 others
* @babel/runtime/helpers/getPrototypeOf in ./node_modules/bootstrap-vue/es/utils/popover.class.js
* @babel/runtime/helpers/inherits in ./node_modules/bootstrap-vue/es/utils/popover.class.js
.........
.........
Was all working fine a few days back, any idea what is causing this?
Thanks for update

**Comment by jackmu95** [comment] 2019-02-18 12:37
Duplicate of #2566, #2587 and #2605.

Fixed via #2595 and will be in the 2.0.0-rc.13 release coming in the next days.

**Closed** 2019-02-18 12:37 UTC
Labels: Status: Coming Soon, Type: Duplicate
