### ISSUE TITLE
Z-index issue with modal and text area

### ISSUE THREAD

**Issue by fabo15x** [bootstrap-vue/bootstrap-vue#4512] opened 2019-12-17 16:07 UTC
### Describe the bug

On IE11 for Windows 10, when a modal is shown, text areas in the background overlap the opened modal as if their z-indexes were the same.
While debugging, I found that BoostrapVue builds modals in a way that might be the cause of this issue:
The HTML shows that:
The wrapper element with suffix "BV_modal_outer" receives the same z-index as its inner element with class "modal_backdrop".
If I change the z-index (1040) that was programatically added by BoostrapVue of "BV_modal_outer" to "auto" the issue is resolved.

![before](https://user-images.githubusercontent.com/4431815/71012501-3f3b9a80-20bd-11ea-8cd5-fab1af1c2066.JPG)
![after](https://user-images.githubusercontent.com/4431815/71012500-3f3b9a80-20bd-11ea-9166-212a21f642ad.JPG)

### Expected behavior

The modal and its content should not conflict with text areas in the background.

### Versions

**Libraries:**

- BootstrapVue: 2.1.0
- Bootstrap: 4.3.1
- Vue: 2.6.10

**Environment:**
- OS: Windows 10
- Browser: IE
- Version: 11

### Additional context

The z-indexes of the text areas in the background are not changed programatically or purposely modified through CSS.

**Comment by tmorehouse** [comment] 2019-12-17 16:17
That z-index is used to handle stacking modals.  if it is removed there will be instances when modals will not stack in the correct order.

**Comment by tmorehouse** [comment] 2019-12-17 17:07
Are you using `static` modal prop?

I just tried a simple mock up with a few text areas in IE11 and can't reproduce the issue.

**Comment by tmorehouse** [comment] 2019-12-17 17:22
Are you including BootstrapVue CSS in your project?

**Comment by tmorehouse** [comment] 2019-12-17 17:42
Could you create a minimum reproduction of the issue?

**Comment by fabo15x** [comment] 2019-12-17 18:08
No, I am not using the "static" prop. Yes, I am including BootstrapVue CSS in my project.
The issue occurs with "Auto height" text areas. You can still replicate the issue with 'no-resize' text areas like in your screenshots if you add enough text so text areas overflow showing the vertical scroll.

**Comment by tmorehouse** [comment] 2019-12-17 18:15
I just added the auto-resize on the text areas and still cannot reproduce the issue:

![image](https://user-images.githubusercontent.com/2781561/71022662-643d0700-20d7-11ea-9653-601d6be136a2.png)

Are you using page transitions on your app that might set an opacity level on the app? I know that opacity will create a new stacking context, but not sure about it as it is only your text areas that are being shifted in z-index (although IE does make form controls higher z-indexes than regular flow elements).

**Comment by fabo15x** [comment] 2019-12-17 19:26
Hi Troy. Thank you for your prompt responses. I'll try to set up a minimum reproduction of the issue. I'm not sure how you were able to use the Online Playground as it doesn't work for me in IE11 on Windows 10. It doesn't even run the default sample. It shows some error about not supporting 'trimRight'.
I'm not using route transitions in my app or any css filter. The backdrop you see in my screenshots come from BootstrapVue.

**Comment by tmorehouse** [comment] 2019-12-17 19:28
I'm using the dev playground which has fixes for the newest babel-standalone (which switched to using `String.prototype.trimLeft/Right` which IE doesn't support)

Just click the version dropdown in the top right and switch to development server

**Comment by fabo15x** [comment] 2019-12-18 18:37
Thanks for the clarification. Unfortunately, I was not able to replicate the issue using the Online Playground. I did however created a minimum reproduction test which allowed me to notice a warning/error coming form BootstrapVue.

![modalCount](https://user-images.githubusercontent.com/4431815/71112805-51d7d180-219a-11ea-8103-768eaf2c90a5.JPG)

I didn't see this error before as it was probably ignored in the dist version I was testing with. While running this minimum reproduction test by using "yarn serve", I was getting the error above **only** when the content of the page is so long that vertical scrollbar of the window appears. A button that triggers a modal is placed at the end of the page, so the only way to get to it is by scrolling to the bottom of the page. Once the button is clicked the warning/error is shown.
This is the minimum reproduction test:
```
<template>
  <div id="app" class="h-100">
	<b-container class="p-0">
		<b-row>
			<b-col>
				<h1 class="text-center font-weight-light">TEXT</h1>
			</b-col>
		</b-row>
		<b-row>
			<b-col>
				<h1 class="text-center font-weight-light">TEXT</h1>
			</b-col>
		</b-row>
		<b-row>
			<b-col>
				<h1 class="text-center font-weight-light">TEXT</h1>
			</b-col>
		</b-row>
		<b-row>
			<b-col>
				<h1 class="text-center font-weight-light">TEXT</h1>
			</b-col>
		</b-row>
		<b-row>
			<b-col>
				<h1 class="text-center font-weight-light">TEXT</h1>
			</b-col>
		</b-row>
		<b-row>
			<b-col>
				<h1 class="text-center font-weight-light">TEXT</h1>
			</b-col>
		</b-row>
		<b-row>
			<b-col>
				<h1 class="text-center font-weight-light">TEXT</h1>
			</b-col>
		</b-row>
		<b-row>
			<b-col>
				<h1 class="text-center font-weight-light">TEXT</h1>
			</b-col>
		</b-row>
		<b-row>
			<b-col>
				<h1 class="text-center font-weight-light">TEXT</h1>
			</b-col>
		</b-row>
		<b-row align-v="center">
			<b-col>
				<router-view/>
			</b-col>
		</b-row>
	</b-container>
	<b-button v-b-modal.modal-1>Launch demo modal</b-button>
	<b-modal id="modal-1" title="BootstrapVue">
		<p class="my-4">Hello from modal!</p>
	</b-modal>
  </div>
</template>
```

**Comment by tmorehouse** [comment] 2019-12-18 19:13
What polyfill are you loading for IE11? babel/polyfill or polyfill.io?

**Comment by tmorehouse** [comment] 2019-12-18 19:19
Here is the markup I created to test in IE:

```html
<!doctype html>
<html lang="en">
<head>
  <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="https://unpkg.com/bootstrap@4.3.1/dist/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="https://unpkg.com/bootstrap-vue@2.1.0/dist/bootstrap-vue.css">
  <script type="text/javascript" src="https://polyfill.io/v3/polyfill.min.js?features=es2015%2CIntersectionObserver" crossorigin="anonymous"></script>
  <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
  <script type="text/javascript" src="https://unpkg.com/bootstrap-vue@2.1.0/dist/bootstrap-vue.js"></script>
</head>
<body>
  <div id="app">
    <div class="h-100">
      <b-container class="p-0">
        <b-row v-for="i in 25" :key="i">
          <b-col>
            <h1 class="text-center font-weight-light">TEXT</h1>
          </b-col>
        </b-row>
      </b-container>
      <b-button v-b-modal.modal-1>Launch demo modal</b-button>
      <b-modal id="modal-1" title="BootstrapVue">
        <p class="my-4">Hello from modal!</p>
      </b-modal>
    </div>
  </div>
  <script type="text/javascript">
    window.onload = function() {
      new Vue({
        el: '#app',
        data: function() {
          return {}
        }
      })
    }
  </script>
</body>
</html>
```

**Comment by fabo15x** [comment] 2019-12-19 21:06
Thanks Troy! I am not able to replicate the issue with your markup, It works just fine. It might come down to the specifics of my project setup.
I'm loading polyfill.io in the index.html, just like in your markup. In addition, I am importing the following packages that might be relevant when supporting IE:
as dependencies:
"@babel/core": "^7.6.0"
"core-js": "^3.4.3"
as devDependencies
"@vue/cli-plugin-babel": "^4.1.0"
"babel-core": "^7.0.0-bridge.0"
"babel-eslint": "^10.0.3"
 "babel-jest": "^23.0.1"
and my babel.config.js file looks like this:
```
module.exports = {
	presets: [
		[
			'@vue/app',
			{
				targets: {
					ie: '11'
				}
			}
		]
	]
};
```

**Comment by tmorehouse** [comment] 2019-12-19 21:12
I'm wondering if you have a polyfill conflict, as you mention you have `polyfill.io` in use, and `core-js` is in your dependencies also

**Closed** 2020-02-13 08:59 UTC
Labels: Status: Details Needed
