### ISSUE TITLE
b-v-toggle does not appear to work with a click handler

### ISSUE THREAD

**Issue by mangyvr** [bootstrap-vue/bootstrap-vue#5475] opened 2020-06-05 01:08 UTC
### Steps to reproduce the bug

We have a link that shows a b-collapse element like this:
```
    <b-card-header header-tag="header" role="tab">
          <a v-b-toggle="'week-' + i" href="#" @click="getDefaults">{{week.dates.join(' - ')}}</a> 
    </b-card-header>
    <b-collapse :id="'week-' + i" accordion="weeks" role="tabpanel" @show="getDefaults">
```

Toggling visibility of the b-collapse element doesn't work unless we remove the @click directive (or set it to have no handler, like in the examples.)

### Expected behavior
Clicking the link should show/hide the b-collapse element, even with an @click handler.

### Versions

**Libraries:**

- BootstrapVue: 2.15.0
- Bootstrap: 4.5.0
- Vue: 2.6.11

**Environment:**

- OS: Linux
- Browser: Firefox 
- Version: 76.0.1

**Comment by Hiws** [comment] 2020-06-05 06:51
This was an issue in version 2.14, but should've been fixed in 2.15.

Your code looks to be working fine for me.
https://codepen.io/Hiws/pen/OJMPZGg

**Comment by mangyvr** [comment] 2020-06-05 19:37
I am unable to duplicate the bug on jsfiddle: https://jsfiddle.net/rgkqtmfv/1/ 
This is pretty close to our setup though.  On playing around more with it, it is not specifically the click handler that's preventing the b-collapse from showing.  If we comment out the two assignments (to the object and array) in the method the @click is calling, the b-collapse shows/hides properly.  Leaving either one causes the b-collapse to not show.  Unsure what could be causing this.

**Comment by Hiws** [comment] 2020-06-18 08:38
Okay.

So i played around with your jsfiddle.
The reason you couldn't reproduce it was because you forgot to add `this.` infront of your variables in the method.

After playing around with it, it seems to be that if you assign a value to a data property that's present in the template, the collapse will no longer open.
You can access them fine and use them. But any assignment will cancel out the collapse.

This appears to be a problem in version `v2.14.0` and above.

So a temporary workaround would be to rollback to version `v.2.13.0` where it should work as intended.

Reproduction of the issue with some comments:
https://codepen.io/Hiws/pen/MWKbxYp

**Comment by mangyvr** [comment] 2020-06-18 16:26
Thanks for catching the missing `this` and reproducing it.  We are currently working around it by using calling the method that assigns those values during @shown for the v-b-toggle instead.

**Comment by sam-araiza** [comment] 2020-06-24 17:38
Using  vue-bootrap over at Riparian LLC. This showed up as a reported bug for us as well. We were only using the click handler to keep track of the state so that we could update the label (Show / Hide) with a caret that would animate 90 deg. We're temporarily fixing this by removing the click handler and having the label only say "Toggle details". Looking forward to the fix. Note that this was not an issue for locally. I had to build and serve to preview the productionized code locally in order to reproduce the behavior, which of course was apparent in production environments.

**Comment by Hiws** [comment] 2020-06-24 17:59
> Using vue-bootrap over at Riparian LLC. This showed up as a reported bug for us as well. We were only using the click handler to keep track of the state so that we could update the label (Show / Hide) with a caret that would animate 90 deg. We're temporarily fixing this by removing the click handler and having the label only say "Toggle details". Looking forward to the fix. Note that this was not an issue for us locally. I had to build and serve to preview the productionized code locally in order to reproduce the behavior, which of course was apparent in production environments.

You can use the `v-model` on `b-collapse` or `b-sidebar`, to get the current state of the component.
This way you don't have to manually toggle the property (i'm guessing), you were toggling in the click event.

Another way would be to do as Mangyvr and use a single method to update the lable and run `this.$root.$emit('bv::toggle::collapse', 'my-collapse-id')`.

**Closed** 2020-08-25 09:59 UTC
Labels: Status: Confirmed, Type: Bug
