### ISSUE TITLE
Docs - Table page not loading

### ISSUE THREAD

**Issue by Tedderouni** [bootstrap-vue/bootstrap-vue#797] opened 2017-08-10 12:23 UTC
When I click on the Table link in the docs, it doesn't load, and gives this error:

Whoops!
resetDetails is not defined

**Comment by tmorehouse** [comment] 2017-08-10 12:47
Duplicate of issue https://github.com/bootstrap-vue/bootstrap-vue/issues/784

This has been fixed with release v0.20.0

**Closed by tmorehouse** 2017-08-10 12:47 UTC
Labels: duplicate
