### ISSUE TITLE
b-img-lazy blank-src is not loaded

### ISSUE THREAD

**Issue by reinoldus** [bootstrap-vue/bootstrap-vue#6470] opened 2021-02-24 15:44 UTC
### Describe the bug

When setting blank-src in the b-img-lazy component that image is never loaded

### Steps to reproduce the bug

1. Go to https://codesandbox.io/s/musing-cohen-o73n9?file=/App.vue:380-414
2. Load page (maybe with slow 3g)

### Expected behavior

I expect b-img-lazy to load the blank src and swap with the original src once downloaded.

### Versions

**Libraries:**

- BootstrapVue: 2.21.2
- Bootstrap: 4.5.3
- Vue: 2.6.12

**Environment:**

- Device: Desktop
- OS: Ubuntu 20.04
- Browser: Chromium
- Version: 88.0.4324.182

### Demo link

https://codesandbox.io/s/musing-cohen-o73n9?file=/App.vue:380-414

Gif showing that there is only 1 request:
![Peek 2021-02-24 17-43](https://user-images.githubusercontent.com/2091290/109026002-f1122600-76c7-11eb-812c-cfa4c44e3a91.gif)

**Comment by Hiws** [comment] 2021-02-24 16:27
Thanks for the report, the issue should already be fixed in the next release.

Duplicate of #6340
Fixed by #6302

**Closed** 2021-02-25 07:40 UTC
Labels: Status: Fixed / Implemented, Type: Duplicate

**Comment by reinoldus** [comment] 2021-03-29 07:12
Thank you for the quick reply, is there an ETA for the release?
