### ISSUE TITLE
Modal - Unable to scroll page after closing during a vue-router guard

### ISSUE THREAD

**Issue by spikeyfish2** [bootstrap-vue/bootstrap-vue#2809] opened 2019-03-10 12:00 UTC
When using a Modal as an 'Are you sure?' type dialog during a navigation change, it prevents the user from being able to scroll the page after they reach the requested page. 

I detect the route changing using _vue-router_'s `beforeNavigationLeave` method. Using the reference to the modal, I call the `show()` method on it to display to the user, and set the `next()` function of _vue-router_ to a local variable in the component. Then, once the user clicks the OK method on the modal, this method is called to continue the navigation. After they land on the requested page, they're unable to scroll. It is also not possible to scroll regardless of route until the user reloads the page in their browser.

I've prepared a test case [here](https://jsfiddle.net/spikeyfish2/rgL3u2wc/7/).

Operating System: Mac OS X 10.14.3
Browser: Google Chrome 72.0.3626.109
Bootstrap Vue: Version 2.0.0-rc.14

**Comment by tmorehouse** [comment] 2019-03-10 17:43
You probably need to use `await` in the guard (and a promise in your modal call) to ensure that the modal closes first before the guard completes. This will allow the modal to remove the classes on the body before the router changes the route.

**Comment by SabreCat** [comment] 2019-03-21 16:57
We at https://github.com/HabitRPG/habitica are finding that since version 2.0.0-rc.12, the `bv::hide::modal` event is not correctly removing the `modal-open` class and `data-modal-open-count` attribute on the document body. That appears to cause the stuck scroll behavior. Could be the same root cause as here?

**Comment by tmorehouse** [comment] 2019-03-21 17:03
It is possible..

Will look into this

**Comment by tmorehouse** [comment] 2019-03-22 01:00
@SabreCat I just did a basic mockup of modals, using $root emit to close them, and the modal-open class and data attribute were properly removed from the body element.

Regarding router guards, you may need to run the `next()` inside of a `$nextTick()` to make sure modal has completed closing before proceeding to the next route, or call next() when modal emits it's hidden event (by doing a $once for the modal hidden, and when fully closed call `next()`).

**Comment by SabreCat** [comment] 2019-03-22 16:51
I wonder what the scenario is that causes the trouble, then, because it's making a mess all over our site. I'm having to strip the class and attributes on `@hide` to work around it.

**Comment by tmorehouse** [comment] 2019-03-22 16:55
It is probably a timing issue, as your route may be changing before modal has had a chance to finish the close transition (or the modal is being destroyed before it had a chance to finish transitioning).

Which is why it would be good to wait for the `hidden` event before letting the route change proceed.

Is the `<b-modal>` inside your `<router-view>` or outside of it?

**Comment by SabreCat** [comment] 2019-03-22 17:46
The affected modals don't change the route, in our case. It's within the same router view.

While tinkering with it just now I found that the document body is correctly updated if I manipulate the `visible` property of the modal rather than emit `bv::hide::modal`...

(If you'd prefer I split this discussion out to a separate ticket, let me know! It just seemed likely to be the same root cause)

**Comment by tmorehouse** [comment] 2019-03-22 20:19
similar/related issue: #2702

**Comment by tmorehouse** [comment] 2019-04-08 16:42
Some of the new behind the scenes fetures introduced by PR #3017 might fix this issue, now that we have a "manager" that looks after the adjustments that are needed to body when modals are opened/closed.  It has a hook on each modal's `beforeDestroy` when they are destroyed to reset the adjustments if no modals are left open.

**Comment by tmorehouse** [comment] 2019-04-08 21:13
@spikeyfish2 could you try with the latest release v2.0.0-rc.18?

**Comment by spikeyfish2** [comment] 2019-04-08 21:20
@tmorehouse Just updated and looks like that's solved the issue now - works as expected. Thank you :).

**Comment by tmorehouse** [comment] 2019-04-08 21:21
Excellent.

**Closed by tmorehouse** 2019-04-08 21:21 UTC
Labels: Status: Answered, Status: Details Needed, Type: Question
