### ISSUE TITLE
DatePicker multiple selection?

### ISSUE THREAD

**Issue by lucapu88** [bootstrap-vue/bootstrap-vue#6187] opened 2020-12-14 10:14 UTC
https://bootstrap-vue.org/docs/components/form-datepicker#form-datepicker

there is no possibility to select multiple dates at the same time?

**Comment by Hiws** [comment] 2020-12-14 10:25
Duplicate of https://github.com/bootstrap-vue/bootstrap-vue/issues/5086
So closing this issue in favor of the other one.

**Closed by Hiws** 2020-12-14 10:25 UTC
