### ISSUE TITLE
Please update bootstrap-vue with bootstrap5. react-bootstrap already updated with bootstrap5.

### ISSUE THREAD

**Issue by suraiyaaysha** [bootstrap-vue/bootstrap-vue#6918] opened 2022-02-18 07:57 UTC
1. Please update bootstrap-vue with bootstrap5. react-bootstrap already updated with bootstrap5. I know that bootstrap4 was jquery dependency that's why you guys made bootstrap-vue. But there are huge useful feature in bootstrap-vue. Please update bootstrap-vue with bootstrap5. Please try to understand and help us.
2. Make full-calendar with task schedule in bootstrap-vue.
3. Please make various feature as like react. In my profession If I search some feature I found most of feature in React but not in Vue.
4. Thanks everyone!

**Comment by Hiws** [comment] 2022-02-18 08:19
Duplicate of: https://github.com/bootstrap-vue/bootstrap-vue/issues/5507

**Closed by Hiws** 2022-02-18 08:19 UTC
