### ISSUE TITLE
Mobile menu incorrectly closes when clicking caret in b-dropdown-item

### ISSUE THREAD

**Issue by jrtitus** [bootstrap-vue/bootstrap-vue#1489] opened 2017-12-24 02:07 UTC
The problem can be seen in the [documentation of the `b-navbar` component](https://bootstrap-vue.js.org/docs/components/navbar) .

### Steps to reproduce

1. Resize the screen to activate the mobile menu
2. Click hamburger icon to open mobile menu
3. Click on one of the carets next to one of the drop-down menu items

You see the drop-down item start to open and then the entire menu closes (slides up).

The problem does not occur in the [official Bootstrap implementation](https://getbootstrap.com/docs/4.0/components/navbar/#nav) (3rd example, containing dropdown item)

**Comment by jrtitus** [comment] 2017-12-24 02:20
I noticed the problem also occurs if you click anywhere in the `padding `of the list item. 

So, it seems you can only click on the drop-down item text `<span>` to avoid the issue.

**Comment by tmorehouse** [comment] 2017-12-24 17:26
Duplicate of #1474 

The fix will be available in the next release

**Closed** 2018-02-15 03:01 UTC
Labels: Status: Coming Soon, Type: Duplicate
