### ISSUE TITLE
Contextual Textarea with max-rows show error icon with bad styling

### ISSUE THREAD

**Issue by boindil** [bootstrap-vue/bootstrap-vue#6414] opened 2021-02-04 15:43 UTC
### Describe the bug

When using a contextual textarea in combination with the property "max-rows", the error icon is partially hidden under a scrollbar.

### Steps to reproduce the bug

Use b-form-textarea with max-rows.

### Expected behavior

The icon is shifted to the left of the scrollbar

### Versions

**Libraries:**

- BootstrapVue: 2.21.1

**Environment:**

- Device: PC
- OS: Windows 10
- Browser: Chrome
- Version: 88.0.4324.104

### Demo link

https://jsfiddle.net/yguad17w/

**Comment by Hiws** [comment] 2021-02-04 15:51
Duplicate of <https://github.com/bootstrap-vue/bootstrap-vue/issues/4781>.

This is an upstream issue with Bootstrap's CSS.
You'll need to write some custom CSS/JS to adjust the icon placement.

**Closed by Hiws** 2021-02-04 15:51 UTC
