### ISSUE TITLE
error bootstrap-vue icons sizes reduced

### ISSUE THREAD

**Issue by mangrove108** [bootstrap-vue/bootstrap-vue#5629] opened 2020-08-01 10:29 UTC
Hello there, i use bootstrap-vue icons and today received this error message while compiling, still the build compiled, and the app works. What should or could be done to prevent this error ? How can i optimize the icons file size ? Thanks

`ERROR  [BABEL] Note: The code generator has deoptimised the styling of /tmp/build_273bc1a4/node_modules/bootstrap-vue/src/icons/icons.js as it exceeds the max of 500KB.`

**Comment by Hiws** [comment] 2020-08-01 10:56
Duplicate of #5627, so closing in favor of that issue.

I would suggest you subscribe to it, so you get a notification once we have a proper answer :)

**Closed by Hiws** 2020-08-01 10:56 UTC
