### ISSUE TITLE
Your website is down

### ISSUE THREAD

**Issue by nejat-njonjo** [bootstrap-vue/bootstrap-vue#5192] opened 2020-04-20 06:32 UTC
## Code: Deployment not found

Your website is down, please fix it.

**Comment by Hiws** [comment] 2020-04-20 07:33
Duplicate of this, which has a workaround:
https://github.com/bootstrap-vue/bootstrap-vue/issues/5186

**Comment by jackmu95** [comment] 2020-04-20 12:02
Closed in favor of #5186.

**Closed by jackmu95** 2020-04-20 12:02 UTC
Labels: Type: Duplicate
