### ISSUE TITLE
Tooltips render differently on hovering multiple times

### ISSUE THREAD

**Issue by jennybalfer** [bootstrap-vue/bootstrap-vue#4558] opened 2020-01-06 11:16 UTC
### Describe the bug

Tooltips on button may appear in different styles when you hover over them multiple times.

![image](https://user-images.githubusercontent.com/44969597/71814977-4f241a00-307e-11ea-9cdc-98147b4f832b.png) 

![image](https://user-images.githubusercontent.com/44969597/71814994-59461880-307e-11ea-95c1-2f8e5f18f876.png)

### Steps to reproduce the bug

1. Go to https://bootstrap-vue.netlify.com/docs/components/tooltip
2. Hover over the first button multiple times

![vue_tooltip](https://user-images.githubusercontent.com/44969597/71814883-14ba7d00-307e-11ea-8351-1e98f9522615.gif)

### Expected behavior

The tooltips should look the same every time you hover over them.

### Versions

Reproducible on https://bootstrap-vue.netlify.com/docs/components/tooltip both in v2.1.0 and Development.

### Demo link

https://bootstrap-vue.netlify.com/docs/components/tooltip

**Comment by jackmu95** [comment] 2020-01-07 08:18
@jennybalfer What you see in the second screenshot is the browsers default button title preview.
This only happens when you hover and unhover over the same button multiple times really fast.

We have to look into this but it's not really a misbehavior.
The problem is that the real tooltip doesn't shows up.

**Comment by tmorehouse** [comment] 2020-01-07 17:53
The real "title" attribute is only removed when the tooltip opens (and restored when it closes). There is a default delay of 50ms before opening and closing a tooltip (which is configurable, and can be set to zero).

The title attribute is not removed until the tooltip opens for accessibility reasons, as screen reader and keyboard-only users cannot hover an element to trigger a tooltip, so the title attribute is left in place so that the value can be read out to screen reader users.

**Closed** 2020-01-08 11:49 UTC
Labels: Status: Answered, Type: Question
