### ISSUE TITLE
Invalid version string "4.0.0-,<5.0.0"

### ISSUE THREAD

**Issue by indicalabs** [bootstrap-vue/bootstrap-vue#511] opened 2017-06-15 17:05 UTC
I added the current version 0.16.1 to my composer , throwing the below exception
  [UnexpectedValueException]                                                                  
  Could not parse version constraint >=4.0.0-,<5.0.0: Invalid version string "4.0.0-,<5.0.0"

**Comment by indicalabs** [comment] 2017-06-15 19:06
also posted at https://github.com/fxpio/composer-asset-plugin/issues/303

I am using composer asset plugin, but there could be a problem with the `- character `

**Comment by tmorehouse** [comment] 2017-06-21 15:03
Have you found out any more about this?

**Comment by indicalabs** [comment] 2017-06-26 10:16
No. 
I am now trying to use this package with  asset-packagist but  asset-packagist is not able to find fetch npm-asset/bootstrap-vue see on Npm
It says 

> Package update failed
> Could you ensure this package exists on npmjs.com?
> Think asset-packagist is guilty? Report on GitHub

I now will report on asset-packagist but I believe there is something wrong with bootstrap-vue.
I will keep updated
https://github.com/hiqdev/asset-packagist/issues/59

**Comment by SilverFire** [comment] 2017-06-29 09:46
NPM [Semver parsing rules](https://docs.npmjs.com/misc/semver) does not allow that `-` sign.

```
$ npm install semver
$ node
> var semver = require('semver')
> semver.satisfies('4.2.1', '>=4.0.0-,<5.0.0')
false
```

**Comment by SilverFire** [comment] 2017-06-29 09:48
Most probably the constraint should be fixed to `>=4.0.0 <5.0.0`

**Comment by alexsasharegan** [comment] 2017-06-29 15:19
Where is this constraint specified? I looked in `package.json`, but I didn't see anything there.

**Comment by tmorehouse** [comment] 2017-06-29 15:20
Might it be inside one of the dependencies packages?

**Comment by indicalabs** [comment] 2017-06-29 20:02
I think the entry "bootstrap": "^4.0.0-alpha.6", in dependencies parsing as  >=4.0.0-,<5.0.0

**Comment by alexsasharegan** [comment] 2017-06-29 20:04
Hmm... I wonder if that could be put in dev-dependencies and/or peer-dependencies. We only ship a copy of the bootstrap css in the dist, so it's used in build and in docs/playground.

**Comment by alexsasharegan** [comment] 2017-07-06 23:03
@indicalabs, I'm going to close this since the issue is outside of our control. I think that the ideal solution to this would be to make NPM work in your build pipeline, but I don't know if that's feasible for you. If NPM is out of the question, I would suggest opening an issue with composer or bootstrap. Feel free to post more info or progress on this, especially if others are in the same boat!

**Closed by alexsasharegan** 2017-07-06 23:03 UTC
Labels: upstream
