### ISSUE TITLE
b-collapse not closing with multiple toggles

### ISSUE THREAD

**Issue by schnetzi** [bootstrap-vue/bootstrap-vue#3856] opened 2019-08-12 12:18 UTC
### Describe the bug
When having two (or more) buttons with `v-b-toggle` only the first button is toggling. The rest of the buttons are not working any more.

### Steps to reproduce the bug

1. go to https://codesandbox.io/embed/vue-template-wsd6v
2. click on "Edit"
3. click on "Cancel" --> working as expected
4. click on "Edit"
5. click on "Save"
6. toggle is not working

### Expected behavior

It should be possible to use `v-b-toggle` with one identifier as often as I want.

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc.27
- Bootstrap: 4.3.1
- Vue: 2.6.10

**Environment:**

- Device: Mac
- OS: macOS Mojave 10.14.6
- Browser: Chrome
- Version: 75

### Demo link

Codesandbox: https://codesandbox.io/embed/vue-template-wsd6v
Github: https://github.com/schnetzi/vue-bootstrap-problem

### Additional context

In version  2.0.0-rc.15 it was still working.

**Comment by jackmu95** [comment] 2019-08-12 13:55
@schnetzi The problem is that you create/destroy the toggles with each time `isEditing` changes. The toggle element itself holds the current state of the collapse to know with state to toggle next. This state get's out of sync by using `v-if` on the buttons.

We may find a way to work around it but since you have your state in `isEditing` anyways you're better off assigning this state to the collapse with the `v-model`.

**Comment by tmorehouse** [comment] 2019-08-12 14:20
Or use `v-show` instead of `v-if` to hide the buttons

**Comment by schnetzi** [comment] 2019-08-12 16:05
@jackmu95, @tmorehouse: thanks a lot for your fast reply. Both solutions worked perfectly for me. Just for reference here my code with `v-model`:

<details><summary>Code</summary>

```
<template>
	<div class="hello">
		<b-input-group>
			<b-form-input
				:id="identifier"
				:placeholder="msg"
				readonly
			></b-form-input>
			<b-input-group-append>
				<b-btn
					variant="outline-secondary"
					v-if="!isEditing"
					@click="edit()"
				>
					Edit
				</b-btn>
				<b-btn
					variant="outline-secondary"
					v-if="isEditing"
					@click="cancel()"
				>
					Cancel
				</b-btn>
				<b-btn variant="success" @click="save()" v-if="isEditing">
					Save
				</b-btn>
			</b-input-group-append>
		</b-input-group>
		<b-collapse v-model="isEditing" :id="identifierCollapse">
			That's a test
		</b-collapse>
	</div>
</template>

<script lang="ts">
import Vue from 'vue';

export default Vue.extend({
	name: 'HelloWorld',
	props: {
		msg: String,
		identifier: String,
	},
	data() {
		return {
			isEditing: false,
		};
	},
	computed: {
		identifierCollapse(): string {
			return `${this.identifier}-collapse`;
		},
	},
	methods: {
		edit() {
			this.isEditing = true;
		},
		cancel() {
			this.isEditing = false;
		},
		save() {
			this.isEditing = false;
		},
	},
});
</script>

<style scoped lang="scss">
...
</style>

```

</details>

**Closed** 2019-08-12 16:05 UTC
Labels: Status: Confirmed, Status: Workaround Available, Type: Question
