### ISSUE TITLE
Error when import bootsrap and bootstrap-vue css

### ISSUE THREAD

**Issue by cihanzengin** [bootstrap-vue/bootstrap-vue#1949] opened 2018-07-19 12:03 UTC
Hello, i got this error when i import boostrap and bootstrap-vue css to my main.js 
here is my files: 

ERROR : 

Failed to compile.

```
./node_modules/css-loader??ref--5-1!./node_modules/postcss-loader/lib??ref--5-2!./node_modules/bootstrap/dist/css/bootstrap.css
Module build failed: BrowserslistError: Unknown browser query `dead`

```

**main.js**

```
import Vue from 'vue'
import App from './App'
import router from './router'
import {store} from './store/store'  // VUEX STORE IMPORT
import BootstrapVue from 'bootstrap-vue'// BOOTSTRAP _ VUE IMPORT 
import 'bootstrap/dist/css/bootstrap.css' 
import 'bootstrap-vue/dist/bootstrap-vue.css'


Vue.use(BootstrapVue);

Vue.config.productionTip = false

/* eslint-disable no-new */
new Vue({
  el: '#app',
  router,
  store,
  components: { App },
  template: '<App/>',
})

```

**package.json** 

```

"scripts": {
    "dev": "webpack-dev-server --inline --progress --config build/webpack.dev.conf.js",
    "start": "npm run dev",
    "build": "node build/build.js"
  },
  "dependencies": {
    "bootstrap-vue": "^2.0.0-rc.11",
    "firebase": "^4.8.0",
    "vue": "^2.5.2",
    "vue-router": "^3.0.1",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "autoprefixer": "^7.1.2",
    "babel-core": "^6.22.1",
    "babel-helper-vue-jsx-merge-props": "^2.0.3",
    "babel-loader": "^7.1.1",
    "babel-plugin-syntax-jsx": "^6.18.0",
    "babel-plugin-transform-runtime": "^6.22.0",
    "babel-plugin-transform-vue-jsx": "^3.5.0",
    "babel-preset-env": "^1.3.2",
    "babel-preset-stage-2": "^6.22.0",
    "chalk": "^2.0.1",
    "copy-webpack-plugin": "^4.0.1",
    "css-loader": "^0.28.11",
    "extract-text-webpack-plugin": "^3.0.0",
    "file-loader": "^1.1.11",
    "friendly-errors-webpack-plugin": "^1.6.1",
    "html-webpack-plugin": "^2.30.1",
    "node-notifier": "^5.1.2",
    "node-sass": "^4.9.2",
    "optimize-css-assets-webpack-plugin": "^3.2.0",
    "ora": "^1.2.0",
    "portfinder": "^1.0.13",
    "postcss-import": "^11.0.0",
    "postcss-loader": "^2.0.8",
    "postcss-url": "^7.2.1",
    "rimraf": "^2.6.0",
    "sass-loader": "^7.0.3",
    "semver": "^5.3.0",
    "shelljs": "^0.7.6",
    "style-loader": "^0.21.0",
    "uglifyjs-webpack-plugin": "^1.1.1",
    "url-loader": "^0.5.9",
    "vue-loader": "^13.3.0",
    "vue-style-loader": "^3.0.1",
    "vue-template-compiler": "^2.5.2",
    "webpack": "^3.6.0",
    "webpack-bundle-analyzer": "^2.9.0",
    "webpack-dev-server": "^2.9.1",
    "webpack-merge": "^4.1.0"
  },
```

**Comment by goroya** [comment] 2018-07-19 13:31
me too

**Comment by pedrovinuela** [comment] 2018-07-21 10:14
Me too

**Comment by klouzoun** [comment] 2018-07-23 16:00
I got the same problem.

**Comment by mosinve** [comment] 2018-07-24 03:54
Duplicate of #1940

**Closed by mosinve** 2018-07-24 03:54 UTC
