### ISSUE TITLE
Background color of dropdown item in Navbar does not go away

### ISSUE THREAD

**Issue by sdr0x07b6** [bootstrap-vue/bootstrap-vue#1374] opened 2017-11-20 06:31 UTC
- Bootstrap v4b2
- BootstrapVue v1.1.0
- Chrome 62

Hi,
Build a submenu using `b-nav-item-dropdown` in the Navbar.
Open the submenu and mouse over each item. Background color and focus ring change.

As it is, when the cursor exits the menu, background color of the last pointed item and focus ring are still attached.

It looks bad.
Above all, in the original Bootstrap 4, background color disappears.
How can we solve it?

- BootstrapVue Submenu
https://bootstrap-vue.js.org/docs/components/navbar/
- Bootstrap Submenu
https://getbootstrap.com/docs/4.0/components/navbar/

Thanks

**Comment by tmorehouse** [comment] 2017-11-20 13:35
This is browser dependent (Firefox works in one way, while Chrome works in another) when it comes to focuis ring styling.

As per ARIA specs, the first item in the dropdown is focused for accessibility reasons.

Duplicate issue with CSS override to adjust styling: https://github.com/bootstrap-vue/bootstrap-vue/issues/1320

Closing as this is by design.

**Closed by tmorehouse** 2017-11-20 13:35 UTC

**Comment by sdr0x07b6** [comment] 2017-11-20 21:53
Sorry that my English is not good.

The appearance of the focus ring does not matter.

When you release (blur, mouseout) the mouse cursor from submenu itself, background color of the last submenu item you were pointing to is still attached.

When you release the mouse on the original Bootstrap 4, background color disappears.

**Comment by tmorehouse** [comment] 2017-11-20 22:34
Could you provide a screenshot of what you are seeing?

**Comment by sdr0x07b6** [comment] 2017-11-20 23:34
Created a screencast.

In Bootstrap4, Each time release mouse cursor from submenu, background color of previous item returns to its original color.

But BoostrapVue leaves the background color intact.


- Original Bootstrap4-beta2
  https://monosnap.com/file/116lJan6UXakseTAtsO0lcmBk78i8F
  - Video source
  https://jsfiddle.net/egj1wzck/

- BoostrapVue1.1.0
https://monosnap.com/file/Xupv5pZL2R1dlsoaGnTsggwG5S45wN

Able to watch it with Chrome and Safari.
(This page could not watch it with Firefox...)

**Comment by tmorehouse** [comment] 2017-11-20 23:39
Ah, what you are seeing is that the menu item gets focused on mouse hover (we trigger focus on mouse hover to make the focus ring move with the mouse, as to not to have two items potentially highlighted in a confusing manner).

Once the menu uses focus (i.e. you click elsewhere), the style goes away (and the menu closes of course).  This is by design for better accessibility reasons.

**Comment by pribilinskiy** [comment] 2017-12-19 12:21
@tmorehouse 
Ok, but there are cases when both Bootstrap and Bootstrap-Vue dropdowns are used on a page.
Bootstrap-Vue styles should not conflict with Bootstrap styles.
imho behaviour should be same in both frameworks.

**Comment by tmorehouse** [comment] 2017-12-19 23:26
There a re some condlocts when using bith bootstrap-vue and bootstrap.js together (conflicting data-attributes needed for styling, but which also trigger native bootstrap on the same components)

**Comment by pribilinskiy** [comment] 2017-12-20 07:16
Is there a list of these conflicts so that users will know about them?
If I know about this I would not perform `yarn add bootstrap-vue`
In that case better to stick with `bootstrap` even though it will be a more verbose markup in a Vue component

**Comment by mosinve** [comment] 2017-12-20 08:02
https://bootstrap-vue.js.org/docs#migrating-a-project-already-using-bootstrap
One can use either BV or Bootstrap jQuery code.

**Comment by pribilinskiy** [comment] 2017-12-20 08:25
@mosinve Thanks, but that's basically says to "get rid of Bootstrap 4 and use Bootstrap-Vue".
What I would like to see is a list of conflicts per component.
The Vue framework itself is designed to be flexible to integrate with other frameworks. One can use both Angular or React with Bootstrap 4 together with Vue components.
As a conclusion Bootstrap-Vue was designed thoughtlessly. 
No explanation on why JS of the original Bootstrap 4 must be removed.
> Conflicting data-attributes needed for styling, but which also trigger native bootstrap on the same components
Would be nice to see some examples and reasons behind these bad design decisions

**Comment by tmorehouse** [comment] 2017-12-23 01:26
The bootstrap v4 team have addressed some of these issues in the upcoming v4.beta.3 release (removing the styling that is triggered via `data-toggle="..."` attributes, and I am sure react and other would have these same conflicts with bootstrap v4.beta.1 and v4.beta.2).
