### ISSUE TITLE
<B-Table> events for $router.push  is not working in Nuxt

### ISSUE THREAD

**Issue by yudhy101** [bootstrap-vue/bootstrap-vue#4465] opened 2019-12-07 14:26 UTC
Hello Guys,

I  just found a weird behaviour related events in B-Table when directing to $router.push().

```
      <b-table
        :fields="table.fields"
        :items="table.items"
        bordered
        hover
        @row-clicked="$router.push({
          path: 'product/list'
        })"
      />
```

i got an error message like below
![image](https://user-images.githubusercontent.com/40293359/70375885-d7a38380-1935-11ea-8fbb-149be39f3ae3.png)

But if i just insert nuxt-link tag somewhere in any slot, the event will work as expected 
```
       <b-table
        :fields="table.fields"
        :items="table.items"
        bordered
        hover
        @row-clicked="$router.push({
          path: 'product/list'
        })"
      >
        <template v-slot:cell(index)="data">
          <nuxt-link to="product/list" />
        </template>
      </b-table>
```

### Versions

**Libraries:**

- BootstrapVue: 2.1.0
- Bootstrap: 4.4.1
- Nuxt : 2.10.2

**Environment:**

- Device: Mac
- OS: macOS Catalina
- Browser: Chrome
- Version: 78.0.3904.108

**Comment by tmorehouse** [comment] 2019-12-07 15:52
Duplicate of https://github.com/bootstrap-vue/bootstrap-vue/issues/4384

This is a bug in the row-hover events of b-table.  Fixed by #4388 and will be available in release  v2.3.0

**Comment by yudhy101** [comment] 2019-12-07 16:00
Oh i see, thanks for clarifying...

**Comment by DharunManivel** [comment] 2019-12-17 15:47
Is there any alternative way to acheive routing without this error ?
I need to route another page and in the mean time have to call a method .
so inside a method i have to route

**Comment by yudhy101** [comment] 2019-12-18 16:09
Hi, as @tmorehouse  mention, it will be release in v2.2.0
But currently, i achieve this using `window.replace`
I don't think my solution is the best, but you can try until the v2.2.0 is release

**Comment by DharunManivel** [comment] 2019-12-19 07:26
but it makes page to load which reset my `state.store`.. anyway thanks :+1:

**Comment by tmorehouse** [comment] 2020-01-09 00:21
BootstrapVue v2.2.0 has been released.

**Closed by tmorehouse** 2020-01-09 00:21 UTC
Labels: Status: Coming Soon, Type: Duplicate
