### ISSUE TITLE
bFormSelect: styling width doesn't match other form components

### ISSUE THREAD

**Issue by alexsasharegan** [bootstrap-vue/bootstrap-vue#312] opened 2017-05-01 17:18 UTC
### Bug
**Description:** The default styling of a form select doesn't match the styling of text inputs.

I've noticed that bootstrap-vue text inputs use the bootstrap class `form-control`, but the select does not use this class unless a size is entered (applied via the `formMixin`). The class `custom-select` seems to be used instead as a base class for the element. 

The css for `custom-select` includes a `max-width: 100%`, but it does not establish a `width`. The bootstrap class `form-control` does apply a `width: 100%` rule.

For now, I've gotten around this by adding the `width: 100%` rule to the `custom-select` class in my own css.

### Rendered Form
![image](https://cloud.githubusercontent.com/assets/16269252/25586857/21e3e868-2e56-11e7-936a-74d6aff876fb.png)

### `.custom-select` styles
![image](https://cloud.githubusercontent.com/assets/16269252/25586992/d7fb0410-2e56-11e7-86c2-d70305411851.png)

### `.form-control` styles
![image](https://cloud.githubusercontent.com/assets/16269252/25587045/11d3a5f2-2e57-11e7-921d-c896eb469ff6.png)

**Comment by tmorehouse** [comment] 2017-05-03 03:37
This might be an issue/feature with Bootstrap V4 alpha 6 CSS:

http://v4-alpha.getbootstrap.com/components/forms/#select-menu

![image](https://cloud.githubusercontent.com/assets/2781561/25647250/bf2ae112-2f96-11e7-94fe-c8670d877d69.png)

By adding `class="form-control"` to `<b-form-select>` such as this:
```html
  <b-form-select v-model="selected" :options="options"  class="form-control">
  </b-form-select>
```

You can get the 100% with back:

![image](https://cloud.githubusercontent.com/assets/2781561/25647449/5249c4bc-2f98-11e7-83c5-0852348a166f.png)

See fiddle https://jsfiddle.net/tmorehouse/c0rmg051/

**Comment by pi0** [comment] 2017-05-03 11:17
@alexsasharegan Is your expected behavior having form-control on form-selects too ?

**Comment by alexsasharegan** [comment] 2017-05-03 16:40
I suppose it is. I can't think of a time I've made a bootstrap form and didn't use their `.form-control[-size]` class. Ultimately, I think it's important to have a clear way to get the `.form-control` class on the component.

**Comment by tmorehouse** [comment] 2017-05-08 22:59
I would think that the select should have the `.form-control` class added, as all other form elements do have `.form-control` (other than radio/check inputs), Especially since this is a `b-form-` component

**Comment by tmorehouse** [comment] 2017-05-18 15:12
So should we add  class `form-control` by default to `b-form-select` to make it match other `b-form-` components?

**Comment by tmorehouse** [comment] 2017-05-23 21:50
I'm thinking we should add form-control to the custom select.

I could add it to my latest PR.

**Comment by tmorehouse** [comment] 2017-06-17 05:27
@alexsasharegan & @pi0 should we add `.form-control` class to the custom select?

**Comment by tmorehouse** [comment] 2017-06-21 13:24
Or should we add a `form-control` prop to enable this feature?

**Comment by tmorehouse** [comment] 2017-06-21 13:28
Actually this is now in the master :smile: from a previous commit.

I'll close the issue

**Closed by tmorehouse** 2017-06-21 13:28 UTC
Labels: bug, enhancement
