### ISSUE TITLE
Bootstrap not loaded starting from BootstrapVue v2

### ISSUE THREAD

**Issue by hepiBatman** [bootstrap-vue/bootstrap-vue#2750] opened 2019-03-02 03:00 UTC
Steps: 
* Create Nuxt project: yarn create nuxt-app
* Add bootstrap snippet to ./pages/index.vue
```
<div class="row">
  <div class="col-md-1">.col-md-1</div>
  <div class="col-md-1">.col-md-1</div>
  <div class="col-md-1">.col-md-1</div>
  <div class="col-md-1">.col-md-1</div>
  <div class="col-md-1">.col-md-1</div>
  <div class="col-md-1">.col-md-1</div>
  <div class="col-md-1">.col-md-1</div>
  <div class="col-md-1">.col-md-1</div>
  <div class="col-md-1">.col-md-1</div>
  <div class="col-md-1">.col-md-1</div>
  <div class="col-md-1">.col-md-1</div>
  <div class="col-md-1">.col-md-1</div>
</div>
```
* You should see from http://localhost:3000 the columns stack up vertically instead of horizontally. If you go to generated .nuxt/App.js you should see bootstrap.css is not imported.

Affected version: bootstrap-vue@2.0.0-rc.0 or later
 ```
 "dependencies": {
    "bootstrap": "^4.1.3",
    "bootstrap-vue": "^2.0.0-rc.0",
    "cross-env": "^5.2.0",
    "nuxt": "^2.3.4",
    "pointer-tracker": "2.0.3",
    "vue": "^2.6.8",
    "vue2-hammer": "^2.1.2"
  },
```
Last known working version: "bootstrap-vue": "^1.5.1"

If it appears to work on your Nuxt project using for 2.0.0-rc.0 onward, perhaps you already downloaded everything prior to the broken version. Delete node_modules, .nuxt, yarn.lock then try again yarn install then yarn dev.

**Comment by tmorehouse** [comment] 2019-03-02 03:18
Duplicate of #2629 and #2725 

See the duplications for interim workaround.  Will be fixed in 2.0.0-rc.14 (coming soon)

**Closed by tmorehouse** 2019-03-02 03:18 UTC
Labels: Type: Duplicate
