### ISSUE TITLE
Make possible setting tooltip onto rows inside b-table

### ISSUE THREAD

**Issue by borishuseincehajic** [bootstrap-vue/bootstrap-vue#6857] opened 2021-11-30 13:08 UTC
Hi,

I was trying to set the tooltip onto tr inside b-table but as far as I see it, it's not possible currently. 
Since there is no scoped slot for the TR itself what remains is usage of tbody-tr-attr attribute of b-table which allows passing custom attributes to the rows. I tried setting that up but it turns out that if you setup something like:

`return {
                    "v-b-tooltip.hover.v-danger":
                        "This tax rate and this account cannot be combined.",
                };`

It will not get recognized. 

Is there a solution to something like this currently to allow using tooltips on the table rows?

Thanks.

**Comment by Hiws** [comment] 2021-11-30 13:40
Duplicate of: https://github.com/bootstrap-vue/bootstrap-vue/issues/5481

**Comment by borishuseincehajic** [comment] 2021-11-30 13:43
Ahh, well in my defense I did try to search the existing issues for it but apparently, it was a bad search. Thanks once more. This can work for me.

**Comment by Hiws** [comment] 2021-11-30 14:06
Searching on GitHub can be pretty terrible 😄

**Closed** 2021-11-30 14:19 UTC
Labels: Type: Duplicate
