### ISSUE TITLE
collapse::toggle::state triggered too many times

### ISSUE THREAD

**Issue by yordis** [bootstrap-vue/bootstrap-vue#569] opened 2017-06-28 09:40 UTC
Everytime I click on the toggle button I see that this emitting happens too many times.

### Versions
- bootstrap-vue: "^0.16.1"
- vue: "^2.3.3"

- [x] Clear the Filter Events
- [x] Other collapser: No

<img width="1539" alt="screen shot 2017-06-28 at 5 39 35 am" src="https://user-images.githubusercontent.com/4237280/27630694-3544ba72-5bc4-11e7-9f22-1982965ebf7c.png">

**Comment by tmorehouse** [comment] 2017-06-28 12:39
Which version of Bootstrap-Vue are you using, and would you be able to provide a simple fiddle showing the issue?

**Comment by alexsasharegan** [comment] 2017-06-28 12:45
Also, be sure to clear your dev tools before testing. I know I've seen my events page be full of old data before.

**Comment by tmorehouse** [comment] 2017-06-28 12:56
Also, do you have any other collapsible elements on your page? Since the state message is emitted to $root, all collapsible elements will receive  copy and filter the event out if it doesn't match the element's ID.

**Comment by yordis** [comment] 2017-06-28 21:46
Working on it!

**Comment by yordis** [comment] 2017-06-28 22:53
@tmorehouse @alexsasharegan I found the issue. Everytime I change the page with `vue-route` it will add an extra call.

**Comment by yordis** [comment] 2017-06-29 00:05
Yeah unless Vue clean the subscription this will never be cleaned up https://github.com/bootstrap-vue/bootstrap-vue/blob/99afe053199ec9d67c06615a4fcef2ae252dfdd6/lib/components/nav-toggle.vue#L52

**Comment by tmorehouse** [comment] 2017-06-29 01:32
Hmmm, I wonder if there are a fw other components that might have this issue (such as modal).

**Comment by alexsasharegan** [comment] 2017-06-29 15:46
This is really curious. I'm also using Vue router, and I don't experience this event duplication. Can you maybe dump in some code from your navbar and it's parent component?

**Comment by tmorehouse** [comment] 2017-06-29 15:48
Also curious if you are using `<keep-alive>` or not.

**Comment by yordis** [comment] 2017-06-29 19:33
@alexsasharegan my App.vue is doing a full replacement. Also I removed every single element and left off with the header from the basic config
```
<template>
  <router-view></router-view>
</template>
```
I am not using any `keep-alive` what is that?

**Comment by tmorehouse** [comment] 2017-06-29 19:35
Keep alive keeps a component in memory on the browser, so that when it is flipped out, and then latter returned, it doesn't have to re-render the component(s). https://vuejs.org/v2/api/#keep-alive

**Comment by alexsasharegan** [comment] 2017-06-29 19:36
So I think we have found the cause. The reason it was a problem was the clutch discovery (at least for me)

**Comment by alexsasharegan** [comment] 2017-06-30 13:38
So PR #574 should fix this, but we're going to try and merge PR #581 in before so we can fix any other components that might be having this problem.

**Comment by tmorehouse** [comment] 2017-06-30 14:34
PR #574 has been merged with master and will be available in v0.17.2

**Comment by alexsasharegan** [comment] 2017-06-30 14:38
@tmorehouse, does that address modals too?

**Comment by alexsasharegan** [comment] 2017-06-30 14:39
I think we said that would be a new PR, but I forget.

**Comment by tmorehouse** [comment] 2017-06-30 14:39
Nope.

Will need a separate PR for that

**Comment by tmorehouse** [comment] 2017-06-30 14:58
PR #593 addresses Modal

**Comment by tmorehouse** [comment] 2017-06-30 18:20
will be available in release v0.17.2

**Closed by tmorehouse** 2017-06-30 18:20 UTC
Labels: bug, coming soon, details needed
