### ISSUE TITLE
Vue 3 Support time [Question]

### ISSUE THREAD

**Issue by fbiagetti** [bootstrap-vue/bootstrap-vue#6260] opened 2020-12-28 14:24 UTC
Good morning friends, I was reading the comments of the support for vue 3 and it does not say anything about a date to be able to use it with vue 3, would anyone have an idea if there is already a way or will the support for vue 3 be soon?

**Comment by Hiws** [comment] 2020-12-28 14:36
Gonna close this as a duplicate of: https://github.com/bootstrap-vue/bootstrap-vue/issues/5196

But to answer the question, an alpha version of BootstrapVue that supports Vue 3 is estimated to the end of this year/January next year.

**Closed by Hiws** 2020-12-28 14:36 UTC
