### ISSUE TITLE
currentPage page's item dom no active

### ISSUE THREAD

**Issue by liangzeng** [bootstrap-vue/bootstrap-vue#1985] opened 2018-08-06 01:45 UTC
```
<input type="number" v-model="currentPage"/>
<b-pagination class="col-sm-12" align="center" size="sm" :total-rows="total" v-model="currentPage" :per-page="10"></b-pagination>
```

change input's value , b-pagination component is change ,but no active css effect.

![image](https://user-images.githubusercontent.com/8503065/43692843-4381ef88-995d-11e8-83af-ebb3cff49652.png)

**Comment by 1207915357** [comment] 2018-08-24 01:47
I have the same problem as you

**Comment by tmorehouse** [comment] 2018-12-16 04:02
Duplicate of #1629

**Closed** 2018-12-16 07:50 UTC
