### ISSUE TITLE
b-modal showing two closes "x" in top right

### ISSUE THREAD

**Issue by Freddie-Banks** [bootstrap-vue/bootstrap-vue#3292] opened 2019-05-14 15:37 UTC
![3rDaqpP](https://user-images.githubusercontent.com/17031052/57711370-7ac54080-7666-11e9-85fc-7d8f7361c31f.png)

**Comment by tmorehouse** [comment] 2019-05-14 15:45
Can you provide a JSFiddle or sample markup you are using?  without knowing this, it is impossible to provide assistance.

**Comment by tmorehouse** [comment] 2019-05-14 16:37
Closing due to lack of details/reproduction

**Closed by tmorehouse** 2019-05-14 16:37 UTC
Labels: Status: Details Needed
