### ISSUE TITLE
Wrong image for arrow icons

### ISSUE THREAD

**Issue by parisaqomi** [bootstrap-vue/bootstrap-vue#6574] opened 2021-04-28 08:34 UTC
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://bootstrap-vue.org/docs/icons

### Additional context or description

Arrow icons which have name with pattern "arrow-*-square" are shown as arrows with circular borders within the docs at https://bootstrap-vue.org/docs/icons but are actually squares when you use them in code, as their names suggest

**Comment by Hiws** [comment] 2021-04-28 08:41
Duplicate of https://github.com/bootstrap-vue/bootstrap-vue/issues/6446

As mentioned in that Issue, it should be fixed in the next release of BootstrapVue.
There's however no ETA when that will be.

**Closed** 2021-04-28 08:41 UTC
Labels: Type: Duplicate
