### ISSUE TITLE
Pagination - @input called for each pagination component

### ISSUE THREAD

**Issue by b-zee** [bootstrap-vue/bootstrap-vue#509] opened 2017-06-15 10:32 UTC
When using two pagination components (e.g. above and below a table) that show the same pagination data, the @input will be called twice.

```
<b-pagination :total-rows="100" :value="page" :per-page="10" @input="toPage"></b-pagination>
<!-- e.g. table -->
<b-pagination :total-rows="100" :value="page" :per-page="10" @input="toPage"></b-pagination>
```

In this case `toPage` will be called twice when using either one of the pagination components:

![image](https://user-images.githubusercontent.com/6576760/27177413-962a398c-51c6-11e7-9c4f-6056cdd24d75.png)
![image](https://user-images.githubusercontent.com/6576760/27177379-75ba8ecc-51c6-11e7-8fac-cf18f79e55d3.png)

**Comment by tmorehouse** [comment] 2017-06-15 14:04
If you bind the pageNumber to both your table and pagination, then you do not need to manually call `toPage(#)` using  `@input`

app:
```js
data: {
  pageNumber: 1
}
```
html:
```html
<b-pagination v-model:"pageNumber"...></b-pagination>
<b-table :current-page="pageNumber"....></b-table>
<b-pagination v-model:"pageNumber"...></b-pagination>
```

**Comment by b-zee** [comment] 2017-06-15 14:48
Sure, but that doesn't explain why `@input` is called for every pagination component.

**Comment by tmorehouse** [comment] 2017-06-15 15:02
That is because you are using `:value="page"`.  And value is being changed on both pagination, so both pagination trigger your @input event.

Replace that with `v-model="value"` on your pagination components, remove the `@input` event altogether, and bind your page number to your b-table as `:current-page="value"`

**Comment by b-zee** [comment] 2017-06-15 15:06
Then where do I place the callback? I'm not using `b-table` and it seems irrelevant to me to bring that up.

**Comment by tmorehouse** [comment] 2017-06-15 15:07
Then, use a watcher on your `value`, and if it changes then call `toPage(#)` in your watcher function.

**Comment by tmorehouse** [comment] 2017-06-15 15:10
Or place `@input="toPage"` only on one of your `b-pagination`

**Comment by b-zee** [comment] 2017-06-15 15:12
Thanks for the suggestions!

However, I still think this issue is a bug, or at least an undesired feature. Your last suggestion would be confusing to my fellow developers.

**Comment by tmorehouse** [comment] 2017-06-15 15:22
Components are self contained, and two pagination components do not know about each other, but in your case they are bound to the same value, so a change in that value will trigger a change on both components, hence each firing the `@input` event whenever the value changes.  It would be similar to biding two text inputs to the same value.  CHanging the content of one text input would also change the content of the other text input.  It is not a bug, as it is the nature of reactivity in Vue.js

**Comment by b-zee** [comment] 2017-06-15 15:39
I understand how the component works, and that apparently the event is coupled to the value. That would also cause the event to be fired if the page is changed programatically (from somewhere completely else, like in the module of Vuex). In my view, that's not what a contained component should do.

Sure, reactivity is the nature of Vue. But, events should not be coupled to a value that I supply myself. An event should be triggered by some event within the component. Like, as I expected, when the user clicks a page, it will trigger an event from that component (like `@click`).

Anyway, consider this closed. I hope documentation will sometime be of higher quality to be clear about the behaviour.

Thanks for helping me out!

**Comment by tmorehouse** [comment] 2017-06-15 15:42
the value for b-pagination should always be bound as a a v-model: `v-model="value"`, as it is an interactive component that works similar to a form input, which fires the @input event (to update the v-model) value.

**Comment by b-zee** [comment] 2017-06-15 15:53
Binding it as a `v-model` does not solve the issue.

The `@input` event is not fired on the form input when the `v-model` of that input changes. So, the pagination component differs from the form input. The Vue `@input` event is exactly what I expected from the `@input` event on the pagination component, and that's why I started this issue. It's still unclear to me why the event would be fired by an external coupled `v-model` value change.

**Comment by tmorehouse** [comment] 2017-06-15 15:56
v-model uses the `input` event to update the parent app's (or component's)  value.  This is the only way to make a prop "two-way" in Vue.js 2.x.x

**Comment by b-zee** [comment] 2017-06-15 16:04
That is perfectly fine. I'm not sure you understand my issue entirely.

Let me explain it from a different, abstract angle: When I think about an `@input` event, I think about something coming from within that component. That event is, like you say, the way to let the parent know something has happened. Good. But, in the case of the pagination component, the event is not fired because the user **inputs** something (a selected page). No, the event is fired because the value changed.

This is undesired, because the event would be fired even when nothing was caused by the pagination component. When changing the page value from within a module in Vuex, by looking at the query parameters in the URL to change on `?page=n`, etc. It is unexpected to have the component firing an event not because of the **user input**, but because of a programmatic change.

**Comment by tmorehouse** [comment] 2017-06-15 16:14
But because the pagination component is a custom input, v-model is required to update the value binding, and by default Vue.js uses the `input` event to do so. (see the Vue.js 2.x docs http://vuejs.org/v2/guide/components.html#Form-Input-Components-using-Custom-Events)

The only option would be to fire a `change` event based on a user clicking (or hitting enter, etc), which would not be fired when the underlying data value is changed.

**Comment by tmorehouse** [comment] 2017-06-15 16:34
I have created a PR to fire the `change` event when the page number changes by user interaction only.

**Comment by tmorehouse** [comment] 2017-06-16 22:14
@b-zee this PR has now been merged into the master.

**Comment by tmorehouse** [comment] 2017-06-29 22:52
v0.17.0 has now been [released](https://github.com/bootstrap-vue/bootstrap-vue/releases/tag/0.17.0) and this issue _should_ be addresed.

Try out the latest, and if you run into issues/bugs, please [create an issue](https://github.com/bootstrap-vue/bootstrap-vue/issues)

**Closed by tmorehouse** 2017-06-29 22:52 UTC
Labels: coming soon, workaround available
