### ISSUE TITLE
Modal overlay missing, Safari on iOS 11.3

### ISSUE THREAD

**Issue by jvb93** [bootstrap-vue/bootstrap-vue#1791] opened 2018-04-30 20:24 UTC
As the title suggests, I’m not seeing the black transparent overlay when a modal is shown. 
This is bad because it allows the site underneath to be interacted with while the modal is shown. 

Reproduce simply by going to [the documentation](https://bootstrap-vue.js.org/docs/components/modal/) and toggling any of the modals in Safari

Tested on iPhone X Safari on iOS 11.3
![7bfa6dc3-bfba-4c21-87e8-718c958ce695](https://user-images.githubusercontent.com/1976577/39448420-b8108390-4c79-11e8-9e52-1b61a3620f08.png)

**Comment by emanuelmutschlechner** [comment] 2018-04-30 21:45
Unable to reproduce this myself as I don't have an iPhone.

@jvb93 Does the site scroll when you swipe top->down on the modal?

**Comment by jvb93** [comment] 2018-04-30 21:53
@emanuelmutschlechner 

So I just re-checked the documentation site on an iPhone and it looks great now, overlay is in place. 

However, the site scrolls underneath if I tap/drag on the modal. Not sure if that's desired functionality or not.

Also, I just re-checked my own project and it is still demonstrating the missing overlay problem on 2.0.0-rc.8

**Comment by emanuelmutschlechner** [comment] 2018-04-30 22:04
Seems like this is a general problem of iOS and Safari:
* [Bootstrap docs: modals - overflow and scrolling on mobile](https://getbootstrap.com/docs/4.1/getting-started/browsers-devices/#overflow-and-scrolling)
* [Boodtrap issue](https://github.com/twbs/bootstrap/issues/22311)
* [Webkit issue: <body> scrolls on iOS](https://bugs.webkit.org/show_bug.cgi?id=153852)

There are some workarounds out there e.g. [this one](https://codeandmortar.com/blog/fed-tips-1/)

**Comment by robcresswell** [comment] 2018-05-08 18:05
Closing as this looks like a general iOS / Safari issue, not BV.

**Closed by robcresswell** 2018-05-08 18:05 UTC
