### ISSUE TITLE
Cannot read property 'props' of undefined when lazy loading <b-col> and <b-form-group> components

### ISSUE THREAD

**Issue by derevandal** [bootstrap-vue/bootstrap-vue#3080] opened 2019-04-10 21:01 UTC
Hi, I'm receiving an error on Nuxt with BootstrapVue v2.0.0-rc.18 when import components individually.

For now, I'm using BootstrapVue v2.0.0-rc.15 without errors.

I'm on Windows 10 with Chrome 73.
[CodeSandbox](https://codesandbox.io/s/m4w7kx8kzx)

**Error:**
> Cannot read property 'props' of undefined

**`pages/index.vue`**
```vue
<template>
  <section>
    <b-jumbotron
      tag="section"
      bg-variant="light"
      text-variant="dark"
      class="mb-0 d-flex justify-content-center align-items-center"
      fluid
    >
      <b-row>
        <b-col>
          <b-card class="h-100">
            Test
          </b-card>
        </b-col>
      </b-row>
    </b-jumbotron>
  </section>
</template>

<script>

export default {
  components: { 
    BJumbotron: () => import('bootstrap-vue/es/components/jumbotron/jumbotron'),
    BCard: () => import('bootstrap-vue/es/components/card/card'),
    BRow: () => import('bootstrap-vue/es/components/layout/row'),
    BCol: () => import('bootstrap-vue/es/components/layout/col')
  }
}
</script>
```

Could someone help me?

**Comment by tmorehouse** [comment] 2019-04-10 23:36
I'm not quite sure what the issue is here, but if you `Vue.use(Layout)` plugin, rather than importing the individual layout components, the issue goes away.  The Layout plugin is pretty light weight, and most likely you would be using these functional components in post places in your app, it would make sense to include it once in your main app or layout.  You can also place it in each page file, and Vue will only install it once - the first time it encounters it.

The `b-col` component (and `b-form-group`) is an async component to begin with (importing it returns a resolvable function rather than a component definition object), as it needs to generate it's breakpoint specific props based on the configured breakpoints in the bootstrap-vue config.

**Comment by tmorehouse** [comment] 2019-04-11 01:29
After a bit of digging through the Vue docs and source code, I have discovered that there are differences in how the following work (https://vuejs.org/v2/guide/components-dynamic-async.html#Async-Components):

```js
Vue.component('foo-bar', () => import('some/dir/foo-bar'))
```
and 
```
export default {
  components: {
    FooBar: () => import('/some/dir/foo-bar')
  }
}
```
The former (`Vue.component(...)`) accepts four types of component definitions:

- Component Plain Object Definition
- `Vue.extend`'ed component constructor
- An async component factory function that calls a `resolve` callback (which returns one of the two above types)
- An async component returns as a `Promise` that will be resolved into one of the first two above types (this is what is happening when you use the async `() => import(...)` format)

While the latter (local usage in a component) also accepts the above types, it appears to not work when the fourth type returns an factory function to the import instead of a Promise (when used in a local component registration)

In our case, since we do not know if the user's browser supports Promises, we return the 3rd option (an async function, rather than a promise).

When using the component group plugins, they call `Vue.component` for each component to be installed, and Vue is happy.

In the case of importing into a local component reference, you are running into the situation of the fourth option, which is not returning a promise to the import. This affects `<b-col>` and `<b-form-group>` when using "lazy loaded components" in the local context of a component.

We can switch these two components to returning Promises, which will work on the majority of common browsers, except: IE <=11, IE Mobile, Opera Mini, and Blackberry browsers. https://caniuse.com/#feat=promises

However, older browsers do require polyfills for many other modern javascript features that BootstrapVue uses (i.e. `Array.from`, `Array.includes`, `Array.some`, `Object.is`, `Object.assign`, `Element.closest`, `Element.matches`, etc), and the majority of these polyfill bundles do provide a polyfill for Promise (i.e. `babel/polyfill`, `polyfill.io`, etc).

We will probably have to switch these two components to return Promises rather than functions that accept a resolve callback.

As a workaround I would suggest loading the Layout plugin, or not using the lazy load async import for `b-col` and `b-form-group`, until Promises are implemented.

**Comment by derevandal** [comment] 2019-04-11 13:13
Thanks man!
So, I'll not use the lazy load async import.

**Closed** 2019-04-20 15:29 UTC
Labels: Status: Coming Soon, Status: Workaround Available, Type: Bug

**Comment by tmorehouse** [comment] 2019-04-21 23:45
Please upgrade to v2.0.0-rc.19 

This should be fixed in the new release
