### ISSUE TITLE
Upgrading rc.11 to rc.12 broke the build due to missing babel package dependency

### ISSUE THREAD

**Issue by 2-5** [bootstrap-vue/bootstrap-vue#2605] opened 2019-02-16 16:20 UTC
It seems that `bootstrap-vue` now has a hard dependency on `babel` which is not declared in it's `package.json`:

    ERROR in ./node_modules/bootstrap-vue/es/directives/scrollspy/scrollspy.class.js
    Module not found: Error: Can't resolve '@babel/runtime/helpers/classCallCheck' in '...\node_modules\bootstrap-vue\es\directives\scrollspy'

    ERROR in ./node_modules/bootstrap-vue/es/components/navbar/navbar.js
    Module not found: Error: Can't resolve '@babel/runtime/helpers/defineProperty' in '...\node_modules\bootstrap-vue\es\components\navbar'

My project uses TypeScript instead of Babel, so the Babel packages are not already present.

**Comment by tmorehouse** [comment] 2019-02-16 16:32
Duplicate of #2566 and #2587.

Fixed via #2595 and will be in the 2.0.0-rc.13 release coming over the weekend.

**Closed** 2019-02-19 02:36 UTC
Labels: Type: Duplicate
