### ISSUE TITLE
Accessibility issue on <b-table>: Elements must only use allowed ARIA attributes

### ISSUE THREAD

**Issue by apavelm** [bootstrap-vue/bootstrap-vue#6588] opened 2021-05-04 01:37 UTC
### ARIA attribute is not allowed: aria-multiselectable="false"

<b-table> is incompatible with Accessibility standards.

**Description**: Ensures ARIA attributes are allowed for an element's role
**Help**: Elements must only use allowed ARIA attributes

**URL for details**: https://dequeuniversity.com/rules/axe/4.1/aria-allowed-attr?application=axeAPI

my implementation:

```
<b-table id="tableName"
           lg="12" md="12" sm="12" class="mb-2"
           selectable
           bordered
           responsive
           fixed
           caption-top
           :head-variant="'light'"
           :select-mode="'single'"
           :fields="fields"
           :items="items"
           small>
```

### Steps to reproduce the bug

1. create <b-table>
2. run accessibility analyzer
3. See error in the report

### Expected behavior

No violation expected

### Versions

**Libraries:**

- BootstrapVue: 2.21.2
- Bootstrap: 4.5.3
- Vue: 2.6.12

**Comment by Hiws** [comment] 2021-05-04 07:17
Looks like this will be fixed in the next release.

Duplicate of: https://github.com/bootstrap-vue/bootstrap-vue/issues/6305
Should be fixed by: https://github.com/bootstrap-vue/bootstrap-vue/pull/6372

**Closed** 2021-05-06 07:16 UTC
Labels: Status: Fixed / Implemented, Type: Duplicate
