### ISSUE TITLE
Invisible tooltip span blocks clickables

### ISSUE THREAD

**Issue by CrixuAMG** [bootstrap-vue/bootstrap-vue#577] opened 2017-06-29 15:09 UTC
I've got a b-tooltip on a page, with above it some inline radiobuttons. I can click them without any issue, but when I hover the tooltip and try again, it no longer is possible, since (even though it is invisible!) it covers the item.
Deleting the div in the devtools fixes this.

**Comment by tmorehouse** [comment] 2017-06-29 15:22
Duplicate of #435 

This should be fixed in the upcoming v0.17.0 release.

**Comment by tmorehouse** [comment] 2017-06-29 22:48
v0.17.0 has now been [released](https://github.com/bootstrap-vue/bootstrap-vue/releases/tag/0.17.0) and this issue _should_ be addresed.

Try out the latest, and if you run into issues/bugs, please [create an issue](https://github.com/bootstrap-vue/bootstrap-vue/issues)

**Closed by tmorehouse** 2017-06-29 22:48 UTC
Labels: coming soon, duplicate
