### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by tsneed290** [bootstrap-vue/bootstrap-vue#161] opened 2017-03-21 21:04 UTC
Requesting unit tests as an enhancement.

**Comment by pi0** [comment] 2017-03-21 21:08
Already on the roadmap :)  We can start implementing them sooner if interested to help on it.

**Comment by tsneed290** [comment] 2017-03-22 13:55
Sounds good. I'm still trying to find a good unit testing pattern for Vue components. Not much material out there (aside from the simple unit test examples). Was going to start checking out various Vue projects for ideas.

**Comment by pi0** [comment] 2017-03-22 14:03
About testing framework if would definitely suggest going with Jest. It has many contributions nowadays and is almost transparently compatible with other test frameworks like AVA and is being used for Facebook and many popular projects. There is already a [vue loader](https://github.com/vire/jest-vue-preprocessor) for jest. I'll try to have some basic tests on a separate branch

**Comment by MarZab** [comment] 2017-05-09 09:10
I've been scolded by recent regressions so I would like to lend a hand in this regard. Any plan of action for unit tests yet?

**Comment by pi0** [comment] 2017-05-18 20:32
So i have prepared [unit tests](https://github.com/bootstrap-vue/bootstrap-vue/tree/master/__tests__/components). They are running with Jest/JSDom & Fixtures are loaded from examples. Actually i have not enough time completing specs. Anyone contribution is super welcome :) You can use [alert.spec.js](https://github.com/bootstrap-vue/bootstrap-vue/blob/master/__tests__/components/alert.spec.js) as a reference to implement other specs.

**Comment by alexsasharegan** [comment] 2017-05-18 20:48
The async support for all this is awesome! And your helper functions are great!

**Comment by alexsasharegan** [comment] 2017-05-18 21:00
Just curious, how does the `expect.toHaveClass` function work? I don't see any `vm.$el._prevClass` array like you've got in here:

```js
expect.extend({
    toHaveClass(vnode, className) {
        return {
            message: `expected to have class '${className}'`,
            pass: vnode.$el._prevClass.indexOf(className) !== -1,
        };
    },
    isComponent(vnode, component) {
        return {
            message: `expected to be ${component}`,
            pass: vnode.$el.constructor.name === component
        };
    },
});
```

**Comment by pi0** [comment] 2017-05-18 21:14
@alexsasharegan Thats an internal Vue variable which is used to set actual class. We may also use `$el.className` too :) (The difference is that _prevClass is not affected by transitions)

**Comment by alexsasharegan** [comment] 2017-05-18 21:15
But doesn't `$el` refer to an actual HTML element?

**Comment by pi0** [comment] 2017-05-18 21:16
Yes it does. Vue injects that reference into Dom :))

**Comment by alexsasharegan** [comment] 2017-05-18 21:21
I see it now. Looks like only when a class is updated. Had to dig through the components to find something that had a class change. Learning all kinds of cool things!

**Comment by alexsasharegan** [comment] 2017-05-22 14:39
@pi0, on the jest matcher function you wrote in `helpers.js` (`toHaveClass`), it takes a string of class names and checks for their presence in the `_prevClass` attribute of vm's `$el`. This can be tricky in two ways:

1. This matches a list of class names **_in exact order_**.  This seems less than ideal since the end-goal is not to validate the order of classes, but the presence of classes. Should this be refactored to take an array of classes to validate? (I can do this and refactor the alert and card specs).
2. This makes it a little awkward when having to validate childnodes of a vm because I cannot write another semantic matcher function, and therefore have to write a class check matcher for plain html elements in each spec.

In respect with #2, I would suggest we break out the matcher into two discrete functions for clarity: `expect().vmToHaveClass` && `expect().elToHaveClass`. Any thoughts? I'd be happy to implement these and PR them along with the button spec I'm working on. I'll refactor the other specs in that case.

I figure it's nice to make this a little easier now, as anything to reduce the friction of writing unit tests is a 👍

**Comment by alexsasharegan** [comment] 2017-05-22 14:43
On second thought, I could write those two new functions (and perhaps accompanying negating functions like vmToNotHaveClass), and they won't collide with the existing ones. Then we can move the other specs over to the different API without making this button spec PR too huge.

**Comment by pi0** [comment] 2017-05-22 14:57
You can always use `.not` modifier to inverse check condition :))

**Comment by alexsasharegan** [comment] 2017-05-22 14:58
Ah, excellent!

**Comment by alexsasharegan** [comment] 2017-05-22 15:38
Any tips on the best way to assert that a child node of a vm is an instance of another component? I'm specifically trying to validate that `<b-link>` gets used on the `<b-button>` when an `href || to` is passed. `expect().toBeInstanceOf()` doesn't like the component definition file because it's an object, not a constructor. Using the `vm.$options._componentTag` seems a little too hacky to me too.

**Comment by pi0** [comment] 2017-05-22 18:05
@alexsasharegan Maybe we can test it based on computed `componentType`  or `:is` prop? Also `_componentTag` seems good idea.

**Comment by alexsasharegan** [comment] 2017-05-22 18:16
Yeah, I thought to look for the `is` prop, but I have no idea where it goes. It seems like Vue consumes and discards it. The computed `componentType` works, but doesn't actually test the rendered element, so I suppose I'll go for the `_componentTag`. I'll guess we'll all be aware the moment that internal prop ever changes!

**Comment by alexsasharegan** [comment] 2017-07-05 19:31
As we now have testing facilities in place, I think we can close this. Roughly speaking, or goal is to progressively add coverage this library as Bootstrap itself becomes more stable. Feel free to PR coverage.

**Closed by alexsasharegan** 2017-07-05 19:31 UTC
Labels: enhancement, on roadmap, unit testing
