### ISSUE TITLE
Issue with the search engine (Algolia)

### ISSUE THREAD

**Issue by Kocal** [bootstrap-vue/bootstrap-vue#2948] opened 2019-03-29 10:21 UTC
Hi,

it looks like URLs in research results are broken. :thinking: 

For example if I search `label`
![Capture d'écran de 2019-03-29 11-15-45](https://user-images.githubusercontent.com/2103975/55226012-427fb500-5214-11e9-95ce-be39b9bccec2.png)

It redirects me to https://bootstrap-vue.js.org/docs/components/layout/docs/components/form-group#label, a page that does not exists:
![Capture d'écran de 2019-03-29 11-15-55](https://user-images.githubusercontent.com/2103975/55226019-457aa580-5214-11e9-99a0-3e2c88471977.png)

And when I refresh the page:
![Capture d'écran de 2019-03-29 11-16-05](https://user-images.githubusercontent.com/2103975/55226018-457aa580-5214-11e9-8b40-2621a4466255.png)

Indeed, the good URL is https://bootstrap-vue.js.org/docs/components/form-group/#label
![Capture d'écran de 2019-03-29 11-16-27](https://user-images.githubusercontent.com/2103975/55226017-457aa580-5214-11e9-9fc1-d288cd884589.png)

I don't know how Algolia Search is implemented on the project, but maybe a trigger an indexation would work?

Thanks!

**Comment by jackmu95** [comment] 2019-03-29 11:53
This is a duplicate of #2945 an was closed by #2947.

**Closed by jackmu95** 2019-03-29 11:53 UTC
Labels: Type: Duplicate

**Comment by Kocal** [comment] 2019-03-29 11:57
Ah my bad, didn't see there was already an issue about it.
