### ISSUE TITLE
Cannot focus input type="password" inside modals on Firefox

### ISSUE THREAD

**Issue by TimoStolz** [bootstrap-vue/bootstrap-vue#1908] opened 2018-06-26 14:41 UTC
**With Firefox 60.0.2, I cannot focus password inputs inside modals.**

Observed behavior: When I click on the password entry, no cursor appears. Expected behavior: When I click on the password entry, a cursor appears and I can start typing.

See the following code or [click here for a fiddle](https://jsfiddle.net/4cv7rqeo/9/):

```html
<div id="app">
  <b-btn v-b-modal.modal-center>open modal</b-btn>

  <b-modal id="modal-center" title="password test">
    <b-form-input type="text"></b-form-input>     <!-- has a cursor -->
    <b-form-input type="password"></b-form-input> <!-- cannot gain focus -->
  </b-modal>
</div>
```

- Operating system: Ubuntu 18.04 (Bionic Beaver) (64bit)
- Browser and version: Firefox 60.0.2 (it works with Chrome!)
- Version of Bootstrap-Vue: 2.0.0-rc.11
- Reduced test case: [JsFiddle](https://jsfiddle.net/4cv7rqeo/9/)

**Comment by n1try** [comment] 2018-08-22 09:44
Got exactly the same problem. Any news on this?

**Comment by tmorehouse** [comment] 2018-08-22 13:00
Does the same thing happen if using a plain `<input type="password">` ?

**Comment by n1try** [comment] 2018-08-22 13:19
Yes, problem is exactly the same when using "native" inputs.

**Comment by tmorehouse** [comment] 2018-10-27 19:05
@TimoStolz @n1try is this issue still happening with latest firefox release (v63)?

**Comment by tmorehouse** [comment] 2018-10-27 19:07
It is possible the cursor is just not showing, but it will still accept input?

**Comment by WhiteRaBot17** [comment] 2018-11-07 19:52
> It is possible the cursor is just not showing, but it will still accept input?

Nope the field simply does not add the input. Its like its be set back to null.

**Comment by tmorehouse** [comment] 2018-11-07 20:42
PR #2100 (merged into dev) may have fixed this (although I still need to make a few more changes, and to share code between `b-form-input` and `b-form-textarea` once I get the textarea PR finished).

**Comment by tmorehouse** [comment] 2018-11-14 02:36
this also sounds like an old chrome bug with passwords (freezing) inside a modal, although that bug has been fixed by chrome.

**Comment by tmorehouse** [comment] 2018-11-14 02:37
does anyone have the same issue using native bootstrap modal's and password fields?

**Comment by WhiteRaBot17** [comment] 2018-11-14 02:39
> does anyone have the same issue using native bootstrap modal's and password fields?

I have used password fields in modals with native bootstrap modals, and it worked as it should.

**Comment by tmorehouse** [comment] 2018-11-14 02:42
interesting.. I'm not sure what is different, as we use the same classes and bootstrap v4.1 native.

**Comment by WhiteRaBot17** [comment] 2018-11-14 02:50
> interesting.. I'm not sure what is different, as we use the same classes and bootstrap v4.1 native.

Not sure. I suspect it has something to do with input[type=password]:focus. If you haven't looked at that css maybe that will help you?

**Comment by WhiteRaBot17** [comment] 2018-11-14 02:52
Side note: If i click with the mouse really fast on the input field while hitting keys I can get 1 dot to appear in the field. If that helps I dont know.

**Comment by tmorehouse** [comment] 2018-11-14 02:52
the native BS v4.1 css for focus?

**Comment by WhiteRaBot17** [comment] 2018-11-14 02:55
> the native BS v4.1 css for focus?

Its probably not the native css, but in the <b-modal> component css could possibly be overriding some of that functionality? Thats a possibility.

**Comment by tmorehouse** [comment] 2018-11-14 02:55
have you tried with the modal prop `no-enforce-focus` set?

**Comment by WhiteRaBot17** [comment] 2018-11-14 02:55
Nope. I'll give it a shot.

**Comment by tmorehouse** [comment] 2018-11-14 02:56
we don't have custom css for modal (not anymore, since it was added to native bootstrap v4.x)

**Comment by WhiteRaBot17** [comment] 2018-11-14 02:58
@tmorehouse It works! no-enforce-focus (I did not even know that was a prop for it). Solved the issue.

Rest easy tonight!!!

**Comment by tmorehouse** [comment] 2018-11-14 03:03
interesting that it causes an issue... I wonder if Firefox changed detection of the document.activeElement with password fields? perhaps to help prevent malicious code form snooping passwords?

**Comment by WhiteRaBot17** [comment] 2018-11-14 03:04
Possibly that'd be a smart move

**Comment by tmorehouse** [comment] 2018-11-14 03:04
I'm guessing when we monitor the focus event during enforce focus (to make sure focus is contained within the modal body element) that firefox does something funky.

**Comment by tmorehouse** [comment] 2018-11-14 03:05
although it is based on the same enforce focus code as bootstrap V4.0 js. may need to check their latest updates, although I did search their issues and didn't find any relating to password inside modal's.

**Comment by WhiteRaBot17** [comment] 2018-11-14 03:07
Well, this solution will work for me and probably for others. Hope I was able to help and thank you!

**Comment by tmorehouse** [comment] 2018-11-14 03:08
I'll label this issue as workaround available (via no `enforce-focus` prop), but it is still an issue that we want to track and find a solution for.

**Comment by tmorehouse** [comment] 2018-11-24 08:31
This sounds like it is a similar issue: https://support.mozilla.org/en-US/questions/1214123

**Comment by tmorehouse** [comment] 2018-11-25 04:16
PR #2215 may address this issue

**Comment by tmorehouse** [comment] 2018-11-25 07:04
@TimoStolz @n1try @mazvv @WhiteRaBot17 

The latest `dev` branch now has a refined enforce focus handler, that is now more aligned with Bootstrap V4.1.

Would you be able to test it out and see if the issue is fixed?

**Comment by tmorehouse** [comment] 2018-12-11 06:59
Closing for now, as we think the issue is addressed in the latest dev branch.

Feel free to open a new issue if you still see the problem in the next release (coming soon)

**Closed by tmorehouse** 2018-12-11 06:59 UTC
Labels: Status: Browser Bug, Status: Workaround Available, Type: Bug
