### ISSUE TITLE
Bootstrap vue support to Vue JS @3.*

### ISSUE THREAD

**Issue by hi2binay** [bootstrap-vue/bootstrap-vue#6712] opened 2021-07-23 09:38 UTC
Bootstrap vue is not working with Vue JS 3.*, please help me on working of it with vue js 3.

**Comment by Hiws** [comment] 2021-07-23 12:11
Duplicate of https://github.com/bootstrap-vue/bootstrap-vue/issues/5196

**Closed by Hiws** 2021-07-23 12:11 UTC
Labels: Type: Duplicate

**Comment by juanchos2018** [comment] 2021-07-29 23:01
ya han usado Bootstrap vue con vue 3 ?
