### ISSUE TITLE
<b-modal> first modal not hiding when no-stacking prop on second modal

### ISSUE THREAD

**Issue by ddweber** [bootstrap-vue/bootstrap-vue#3221] opened 2019-05-02 07:08 UTC
**Expected behaviour:**
When `no-stacking` prop is placed on a second modal the first modal gets hidden when the second is triggered to show up. (Like a singleton)

**Actual behaviour:**
Nothing happens when the second modal is triggered to show up.
Have a look at this [fiddle.](https://jsfiddle.net/j52ury1p/1/)

**Comment:**
Is this by design or a bug?

**Comment by tmorehouse** [comment] 2019-05-02 12:56
By design.

when no-stacking is enabled, the modal will not open up until the previously opened modal (if there is one) has been closed by the user.

**Comment by ddweber** [comment] 2019-05-02 13:56
Ok, thanks for the answear :)

Is there a way to trigger both (stacking OR no-stacking second modal) from the first modal? Maybe via reactive `no-stacking` property?

**Comment by tmorehouse** [comment] 2019-05-02 13:57
You could add some logic, listening for root events, or trigger a `hide` on the first modal before the second modal is opened.

**Closed** 2019-05-02 14:05 UTC
Labels: Status: Answered, Type: Question

**Comment by pratibhabarad** [comment] 2022-02-03 12:34
<div id="app">
  <div>
    <b-button v-b-modal.modal-multi-1>Open First Modal</b-button>

    <b-modal id="modal-multi-1" size="lg" title="First Modal" ok-only no-stacking>
      <p class="my-2">First Modal</p>
      <b-button v-b-modal.modal-multi-2a>Open Second Modal (stacking)</b-button>

    </b-modal>

    <b-modal id="modal-multi-2a" title="Second Modal" ok-only>
      <p class="my-2">Second Modal (stacking)</p>
      <b-button v-b-modal.modal-multi-3 size="sm">Open Third Modal</b-button>
    </b-modal>

    <b-modal id="modal-multi-3" size="sm" title="Third Modal" ok-only>
      <p class="my-1">Third Modal</p>
    </b-modal>
  </div>
</div>
