### ISSUE TITLE
B-Table set selected rows programmatically

### ISSUE THREAD

**Issue by bomanti** [bootstrap-vue/bootstrap-vue#3370] opened 2019-05-23 21:01 UTC
Hi,

A feature request;
It will be nice to set selectedRows programmatically.

When i try to set this.$refs.table.selectedRows = [this.selectedItem]; always setting first element of rows

Thank you

**Comment by tmorehouse** [comment] 2019-05-23 23:07
`selectedRows` is an internal sparse array and should not be used by humans (plus it may change in the future)

Duplicate of #2687 and partially #3064

**Closed** 2019-05-25 00:17 UTC
Labels: Type: Duplicate, Type: Feature request

**Comment by omnigodepot** [comment] 2019-06-05 23:06
Is there any way to set a selected row in the table?

**Comment by tmorehouse** [comment] 2019-06-05 23:08
@omnigodepot see https://github.com/bootstrap-vue/bootstrap-vue/issues/2687#issuecomment-466395945 for a way to "click" a row to select it.
