### ISSUE TITLE
Modal Property close-on-backdrop doesn't work.

### ISSUE THREAD

**Issue by Catrionaa** [bootstrap-vue/bootstrap-vue#423] opened 2017-05-19 11:04 UTC
When setting the modal property "close-on-backdrop" to false, When clicking on the backdrop it still closes.

**Comment by tmorehouse** [comment] 2017-05-19 11:39
THis might just be a simple fix in the handler.

**Comment by tmorehouse** [comment] 2017-05-19 12:54
Hmmm this is strange.  The logic is there to prevent clocking when `close-on-backdrop="false"`, but it is still closing.  And `close-on-esc="false"` is also not working (and it has the logic there as well).

**Comment by tmorehouse** [comment] 2017-05-19 13:12
Ah, even though the two props are set to `Boolean`, when setting the props to `false`, the actual value is being returned by `this.closeOnBackdrop` (and `this.closeOnEsc`) is the string `"false"`, rather than the Boolean value `false`.  It appears Vue.js is not converting the string values of the attributes to boolean.

**Comment by alexsasharegan** [comment] 2017-05-19 13:20
Oh, that makes sense. I was going to say that it's working for me. If you want to pass anything other than a string, you'll have to use the attribute binding syntax.

**Comment by tmorehouse** [comment] 2017-05-19 13:33
the `fade` prop is similar, it needs to be `v-bind` as well to disable the transition animation

**Comment by tmorehouse** [comment] 2017-05-19 13:36
So not really sure if this could be classified as a bug, but rather "needs clarity" in documentation.

I can add a few extra tests for prop `!== 'false'` to get around the need for binding.

**Comment by tmorehouse** [comment] 2017-05-19 13:38
Or we change the props to be `noCloseonEsc` and `noCloseOnBackdrop` (and default to `false`).  This might be a breaking change for some users though.

**Comment by alexsasharegan** [comment] 2017-05-19 13:47
For booleans, the presence or absence of the prop also generated the corresponding boolean.

**Comment by tmorehouse** [comment] 2017-05-19 14:04
Yeah, and with  default of `true` it is not possible to rely just on presence or absence.  I can add in the extra test for `!== 'false' as a simple workaround.

**Comment by alexsasharegan** [comment] 2017-05-19 14:09
Oh, true is the default! Yeah, I guess in hindsight, it would have been better to use a negative attribute to enable that syntax.

**Comment by alexsasharegan** [comment] 2017-05-19 14:10
Maybe pin that one for major release with breaking changes.

**Comment by tmorehouse** [comment] 2017-05-19 14:13
Would also have to change `fade` to `noFade` (defaulted to `false`).

@pi0 what are your thoughts on changing the boolean props (which default to `true`) to negative props (defaulting to `false`)?

**Comment by tmorehouse** [comment] 2017-05-19 14:18
`fade` could be changed to default to `false`, as when using vanilla bootstrap you need to add the `fade` class to the modal. As for `closeOnEsc` and `closeOnBackdrop`, maybe they could be changed to `noCloseOnEsc` and `noCloseOnBackdrop` (both defaulting to `false`), rather than adding extra logic to test for `!== 'false'`

**Comment by alexsasharegan** [comment] 2017-05-19 14:27
Maybe a micro-optimization here, but you wouldn't even need to define a default. If nothing is present, the undefined value will work just like a default of `false`.

**Comment by tmorehouse** [comment] 2017-05-19 14:29
True. would save some bytes in the code footprint, although wouldn't be as clear in the documentation as to the default value.

**Comment by alexsasharegan** [comment] 2017-05-19 14:40
Yeah, you guys have that cool API generation stuff that feeds off the prop definitions, don't you?

**Comment by tmorehouse** [comment] 2017-05-19 14:42
Yeah, the documentation generates the list of props based on the component props definition I believe.

**Comment by pi0** [comment] 2017-05-19 14:42
That could be patched to support prop only mode too :)

**Comment by alexsasharegan** [comment] 2017-05-19 14:45
If the docs can display definitions for the _prop only_ style, I think that's optimal. It's the most like plain HTML and doesn't even require attribute binding syntax—which means it's easier for beginners to Vue to get right.

**Comment by tmorehouse** [comment] 2017-05-19 14:48
So @pi0 what do you think about changing the `closeOn...` props to `noCloseOn...`, and defaulting `fade` to `false` (or no default)?

**Comment by pi0** [comment] 2017-05-19 14:51
`no-prop` is always more semantic than `:prop=false` :D Buy why disable fade by default ?

**Comment by tmorehouse** [comment] 2017-05-19 14:53
`fade` is a boolean defaults to `true` and using `fade="false"` doesn't disable the transition animations (unless you use `:fade="false"` to convert `"false"` into a boolean `false`)

**Comment by pi0** [comment] 2017-05-19 14:53
so we can use `no-fade` instead?

**Comment by alexsasharegan** [comment] 2017-05-19 14:54
Agreed on `no-fade`, since majority use case is with fade transitions.

**Comment by tmorehouse** [comment] 2017-05-19 14:55
that is an option too.  Although with bootstrap vanilla you have to explicitly add the class `fade` to the modal to get animations.

But it is true that most want the animation.

**Comment by tmorehouse** [comment] 2017-05-19 14:59
The slide down is in the BS css, but it appears that it gets botched a bit because of v-show/v-if usage/timing

**Comment by tmorehouse** [comment] 2017-05-19 15:00
So should I remove the defaults from the new `noCloseOn...` and `noFade` (since they will be false by default), or wit until the docs are patched to handle *prop only*?

**Comment by alexsasharegan** [comment] 2017-05-19 15:01
Maybe you could patch that on a branch that sits ready to merge until doc generation and such get updated.

**Comment by tmorehouse** [comment] 2017-05-19 15:07
Yeah, I have  branch on my fork all ready to go (but with the defaults of `false` set).

**Comment by mosinve** [comment] 2017-05-19 17:34
It's a known fact that assigning a `false` value done with v-bind ... it's not a bug...  I think I meet this info somewhere in official Vue docs

**Comment by mosinve** [comment] 2017-05-19 17:42
so i think is a whole not a bug... is just about correct use of syntax.

**Comment by mosinve** [comment] 2017-05-19 17:47
But for better usability, default boolean values must be false. It's more natural - if not explicitly declared - then it's false

**Comment by tmorehouse** [comment] 2017-05-19 22:25
@Catrionaa thi should be fixed in the latest master, but note that the props are renamed `no-close-on-esc` and `no-close-on-backdrop` for disabling the feature.

Expect this to be in the next release

**Closed by tmorehouse** 2017-05-19 22:25 UTC
